<section class="page-head"><div><p class="eyebrow">Pusat kendali</p><h2>Ringkasan kondisi air</h2><p>Data operasional terbaru dari seluruh perangkat pemantauan.</p></div><div class="live-chip"><span></span> Pembaruan otomatis</div></section>
<?php $cards=[
 ['locations','Lokasi','bi-geo-alt','#2563eb'],['devices','Total Alat','bi-router','#7c3aed'],['active_devices','Alat Aktif','bi-check-circle','#059669'],
 ['offline_devices','Alat Offline','bi-wifi-off','#dc2626'],['maintenance_devices','Dalam Perawatan','bi-tools','#d97706'],['sensors','Sensor','bi-speedometer2','#0891b2'],
 ['readings_today','Data Hari Ini','bi-database-check','#4f46e5'],['active_alerts','Peringatan Aktif','bi-bell','#e11d48']
];?><div class="stats-grid"><?php foreach($cards as [$key,$label,$icon,$color]):?><article class="stat-card"><div class="stat-icon" style="--accent:<?=$color?>"><i class="bi <?=$icon?>"></i></div><div><span><?=$label?></span><strong data-stat="<?=$key?>"><?=number_format((int)($stats[$key]??0),0,',','.')?></strong></div></article><?php endforeach?></div>
<div class="dashboard-grid"><section class="panel chart-panel"><div class="panel-head"><div><h3>Tren Parameter Utama</h3><p>Tujuh hari terakhir</p></div><select id="chartParameter" class="form-select form-select-sm"><option value="debit">Debit</option><option value="tinggi_muka_air">Tinggi muka air</option><option value="ph">pH</option><option value="suhu_air">Suhu air</option><option value="tds">TDS</option></select></div><div class="chart-wrap"><canvas id="mainChart" data-chart='<?=e(json_encode($charts))?>'></canvas></div></section>
<section class="panel status-panel"><div class="panel-head"><div><h3>Status Perangkat</h3><p>Ketersediaan jaringan</p></div></div><div class="donut-wrap"><canvas id="statusChart" data-active="<?=e($stats['active_devices']??0)?>" data-offline="<?=e($stats['offline_devices']??0)?>" data-maintenance="<?=e($stats['maintenance_devices']??0)?>"></canvas></div><div class="status-legend"><span><i class="normal"></i> Aktif</span><span><i class="danger"></i> Offline</span><span><i class="warning"></i> Perawatan</span></div></section></div>
<div class="quick-grid"><a href="<?=url('monitoring')?>"><i class="bi bi-activity"></i><span><strong>Monitoring langsung</strong><small>Lihat data sensor terbaru</small></span><i class="bi bi-chevron-right"></i></a><a href="<?=url('map')?>"><i class="bi bi-map"></i><span><strong>Peta lokasi</strong><small>Pantau sebaran perangkat</small></span><i class="bi bi-chevron-right"></i></a><a href="<?=url('alerts')?>"><i class="bi bi-bell"></i><span><strong>Peringatan</strong><small>Tindak lanjuti anomali</small></span><i class="bi bi-chevron-right"></i></a></div>
<script>window.dashboardRefresh=<?=json_encode((int)\App\Core\Env::get('DASHBOARD_REFRESH_SECONDS',30))?>;</script>

