<main class="auth-wrap"><section class="auth-panel auth-brand-panel"><div><span class="water-logo"><i class="bi bi-droplet-half"></i></span><p class="eyebrow">Sistem Terintegrasi</p><h1>Data air yang akurat untuk keputusan yang lebih baik.</h1><p>Pantau ketinggian, debit, dan kualitas air dari seluruh lokasi secara real-time.</p></div><div class="auth-metric-row"><div><strong>24/7</strong><span>Pemantauan</span></div><div><strong>IoT</strong><span>Terintegrasi</span></div><div><strong>WITA</strong><span>Zona waktu</span></div></div></section>
<section class="auth-panel auth-form-panel"><div class="login-box"><div class="mobile-logo"><span class="water-logo"><i class="bi bi-droplet-half"></i></span></div><p class="eyebrow">Selamat datang kembali</p><h2>Masuk ke SIMMA</h2><p class="text-secondary mb-4">Gunakan akun petugas yang telah terdaftar.</p>
<form method="post" action="<?=url('login')?>" class="vstack gap-3"><?=csrf_field()?>
<div><label class="form-label">Username atau email <span class="required-mark">*</span></label><div class="input-icon"><i class="bi bi-person"></i><input class="form-control" name="identity" autocomplete="username" required autofocus placeholder="contoh: admin"></div></div>
<div><div class="d-flex justify-content-between"><label class="form-label">Kata sandi <span class="required-mark">*</span></label><a href="#" class="small">Lupa kata sandi?</a></div><div class="input-icon"><i class="bi bi-lock"></i><input id="password" type="password" class="form-control" name="password" autocomplete="current-password" required><button type="button" class="password-toggle" data-toggle-password="#password"><i class="bi bi-eye"></i></button></div></div>
<?php if(isset($_SESSION['captcha_answer'])):?><div><label class="form-label">Verifikasi: berapa <?=e($_SESSION['captcha_a'])?> + <?=e($_SESSION['captcha_b'])?>?</label><input class="form-control" type="number" name="captcha" required></div><?php endif?>
<div class="form-check"><input class="form-check-input" type="checkbox" name="remember" id="remember"><label class="form-check-label" for="remember">Ingat saya di perangkat ini</label></div>
<button class="btn btn-primary btn-lg">Masuk <i class="bi bi-arrow-right ms-1"></i></button></form>
<p class="login-hint"><i class="bi bi-shield-check"></i> Koneksi aman · Percobaan login dibatasi</p><p class="version">SIMMA versi 1.0.0</p></div></section></main>
