<?php
declare(strict_types=1);
spl_autoload_register(function(string $class): void {$prefix='App\\';if(!str_starts_with($class,$prefix))return;$file=dirname(__DIR__).'/app/'.str_replace('\\','/',substr($class,strlen($prefix))).'.php';if(is_file($file))require $file;});
use App\Services\DesignOptimizationService;use App\Services\DesignValidationService;
$failed=[];$assert=function(bool $condition,string $message)use(&$failed){echo ($condition?'[PASS] ':'[FAIL] ').$message.PHP_EOL;if(!$condition)$failed[]=$message;};
$service=new DesignOptimizationService();$ranked=$service->rankAlternatives([
 ['combination_code'=>'MURAH-GAGAL','total_cost'=>1,'total_headloss_m'=>1,'minimum_pressure_m'=>-8,'maximum_velocity_mps'=>5,'status'=>'FAIL','converged'=>true],
 ['combination_code'=>'LOLOS-2','total_cost'=>200,'total_headloss_m'=>3,'minimum_pressure_m'=>18,'maximum_velocity_mps'=>1.1,'status'=>'PASS','converged'=>true],
 ['combination_code'=>'LOLOS-1','total_cost'=>100,'total_headloss_m'=>4,'minimum_pressure_m'=>17,'maximum_velocity_mps'=>1.3,'status'=>'PASS','converged'=>true],
 ['combination_code'=>'TIDAK-KONVERGEN','total_cost'=>.5,'total_headloss_m'=>0,'minimum_pressure_m'=>20,'maximum_velocity_mps'=>1.2,'status'=>'PASS','converged'=>false],
],'LOWEST_INITIAL_COST');
$assert($ranked[0]['combination_code']==='LOLOS-1'&&$ranked[0]['is_recommended'],'Alternatif gagal/nonkonvergen tidak dapat menang');$assert(end($ranked)['combination_code']==='TIDAK-KONVERGEN'||end($ranked)['combination_code']==='MURAH-GAGAL','Alternatif tidak valid diletakkan setelah alternatif lolos');
$nearestFailed=$service->rankAlternatives([['combination_code'=>'MURAH-BANYAK-GAGAL','total_cost'=>1,'status'=>'FAIL','converged'=>true,'failure_reasons'=>['a','b','c']],['combination_code'=>'DEKAT-SATU-GAGAL','total_cost'=>100,'status'=>'FAIL','converged'=>true,'failure_reasons'=>['a']]],'BALANCED');$assert($nearestFailed[0]['combination_code']==='DEKAT-SATU-GAGAL','Alternatif terdekat dipilih dari jumlah pelanggaran paling sedikit');
$balanced=$service->rankAlternatives([['combination_code'=>'MURAH-TIDAK-SEIMBANG','total_cost'=>1,'total_headloss_m'=>10,'minimum_pressure_m'=>10,'maximum_pressure_m'=>55,'minimum_velocity_mps'=>.2,'maximum_velocity_mps'=>.3,'status'=>'PASS','converged'=>true],['combination_code'=>'SEIMBANG','total_cost'=>100,'total_headloss_m'=>5,'minimum_pressure_m'=>20,'maximum_pressure_m'=>35,'minimum_velocity_mps'=>1.1,'maximum_velocity_mps'=>1.3,'status'=>'PASS','converged'=>true]],'BALANCED',[],['target_pressure_m'=>20,'target_velocity_mps'=>1.2]);$assert($balanced[0]['combination_code']==='SEIMBANG','Desain seimbang memprioritaskan gabungan target tekanan, kecepatan, headloss, dan keselamatan');
$model=['links'=>[['id'=>7,'link_type'=>'PIPE','route_name'=>'P-7','planned_flow_lps'=>10,'max_pipe_capacity_lps'=>10]]];$catalog=[['id'=>1,'dn_mm'=>100,'inside_diameter_mm'=>90],['id'=>2,'dn_mm'=>150,'inside_diameter_mm'=>135]];
$sets=$service->candidateSets($model,[['network_link_id'=>7,'is_diameter_locked'=>1,'fixed_catalog_id'=>2]],$catalog,1.2);$assert(count($sets[7])===1&&(int)$sets[7][0]['id']===2,'Diameter terkunci hanya menghasilkan satu kandidat');
$freeCatalog=[['id'=>3,'material'=>'HDPE','dn_mm'=>110,'outside_diameter_mm'=>110,'wall_thickness_mm'=>10,'inside_diameter_mm'=>90,'pressure_class'=>'PN10','allowable_pressure_bar'=>10,'hazen_williams_c'=>150,'darcy_roughness_mm'=>.0015,'price_per_meter'=>100000]];
$freeSets=$service->candidateSets($model,[['network_link_id'=>7,'is_diameter_locked'=>0,'allowed_catalog_ids'=>[3],'diameter_group'=>'__FREE__']],$freeCatalog,['minimum_velocity_mps'=>.6,'target_velocity_mps'=>1.2,'maximum_velocity_mps'=>2]);$freeDiameters=array_column($freeSets[7],'inside_diameter_mm');$assert(count($freeDiameters)>3&&!in_array(90.0,$freeDiameters,true)&&count(array_filter($freeDiameters,fn($diameter)=>abs($diameter-round($diameter))>.0001))>0,'Mode diameter bebas menghasilkan beberapa ukuran desimal di luar DN katalog');
$validation=(new DesignValidationService())->evaluateScenario(['node:1'=>['pressure_m'=>5,'requested_demand_lps'=>1]],['link:1'=>['velocity_mps'=>.2,'headloss_m'=>2,'unit_headloss_m_per_km'=>20]],['minimum_pressure_m'=>10,'maximum_pressure_m'=>60,'minimum_velocity_mps'=>.6,'maximum_velocity_mps'=>2,'minimum_velocity_active'=>1,'maximum_unit_headloss_active'=>1,'maximum_unit_headloss_m_per_km'=>10],['link:1'=>['allowable_pressure_bar'=>10]]);$assert(!$validation['passed']&&count($validation['reasons'])>=3,'Tekanan, kecepatan, dan headloss yang gagal dicatat lengkap');
$strictLowDemand=(new DesignValidationService())->evaluateScenario([],['link:1'=>['velocity_mps'=>.59,'headloss_m'=>1,'unit_headloss_m_per_km'=>2]],['minimum_velocity_mps'=>.6,'maximum_velocity_mps'=>2,'minimum_velocity_active'=>1,'allow_low_velocity'=>0,'maximum_unit_headloss_active'=>1,'maximum_unit_headloss_m_per_km'=>10],['link:1'=>['allowable_pressure_bar'=>10]]);$assert(!$strictLowDemand['passed']&&str_contains(implode(' ',$strictLowDemand['reasons']),'terlalu rendah'),'Desain seimbang menolak kecepatan jam rendah yang kurang dari batas wajib');
$boundaryValidation=(new DesignValidationService())->evaluateScenario(['source:1'=>['pressure_m'=>0,'node_type'=>'reservoir','entity_type'=>'source'],'reservoir:1'=>['pressure_m'=>0,'node_type'=>'reservoir','entity_type'=>'node']],['link:1'=>['velocity_mps'=>1.2,'headloss_m'=>31,'unit_headloss_m_per_km'=>10.31,'fixed_head_boundary_link'=>true]],['minimum_pressure_m'=>10,'maximum_pressure_m'=>60,'minimum_velocity_mps'=>.6,'maximum_velocity_mps'=>2,'minimum_velocity_active'=>1,'maximum_unit_headloss_active'=>1,'maximum_unit_headloss_m_per_km'=>10],['link:1'=>['allowable_pressure_bar'=>10]]);$assert($boundaryValidation['passed']&&count($boundaryValidation['warnings'])===1,'Headloss antar dua muka energi tetap menjadi peringatan karena tidak dapat diturunkan hanya dengan diameter');
$transitValidation=(new DesignValidationService())->evaluateScenario(['node:118'=>['pressure_m'=>154.81,'node_type'=>'junction','entity_type'=>'node','requested_demand_lps'=>0]],[],['minimum_pressure_m'=>10,'maximum_pressure_m'=>60],[]);$assert($transitValidation['passed']&&$transitValidation['nodes']['node:118']['status']==='TRANSIT','Junction transmisi tanpa demand tidak gagal oleh batas tekanan pelayanan');
$pumpValidation=(new DesignValidationService())->evaluateScenario([],['link:1'=>['network_link_id'=>1,'velocity_mps'=>1.1,'headloss_m'=>1,'unit_headloss_m_per_km'=>2],'link:2'=>['network_link_id'=>2,'velocity_mps'=>0,'headloss_m'=>0,'unit_headloss_m_per_km'=>0]],['minimum_velocity_mps'=>.6,'maximum_velocity_mps'=>2,'minimum_velocity_active'=>1,'maximum_unit_headloss_active'=>1,'maximum_unit_headloss_m_per_km'=>10],['link:1'=>['allowable_pressure_bar'=>10]]);$assert($pumpValidation['passed']&&isset($pumpValidation['links']['link:1'])&&!isset($pumpValidation['links']['link:2']),'Pompa tanpa diameter tidak dimasukkan ke hasil desain pipa');
$endpointValidation=(new DesignValidationService())->validateConfiguration(['name'=>'Uji','hydraulic_method'=>'H-W'],['minimum_velocity_mps'=>.6,'maximum_velocity_mps'=>2,'minimum_pressure_m'=>10,'maximum_pressure_m'=>60],[['network_link_id'=>1,'route_name'=>'Pipa A-B','pipe_length_m'=>10,'origin_type'=>'node','origin_id'=>1,'destination_type'=>'node','destination_id'=>2,'allowed_catalog_ids'=>[1]]],[1=>['id'=>1]]);$assert($endpointValidation['valid'],'Endpoint berbeda berbasis type/id tidak salah dianggap sama');
$nodes=['source:1'=>['key'=>'source:1','entity_type'=>'node','id'=>1,'engine_id'=>'R1','name'=>'Sumber','node_type'=>'reservoir','elevation_m'=>80,'head_m'=>100,'total_head_m'=>100,'x'=>5,'y'=>50]];for($i=1;$i<=5;$i++)$nodes['node:'.$i]=['key'=>'node:'.$i,'entity_type'=>'node','id'=>$i+1,'engine_id'=>'J'.$i,'name'=>'Node '.$i,'node_type'=>'junction','elevation_m'=>40+$i,'base_demand_lps'=>$i===5?1:.25,'demand_pattern_id'=>null,'emitter_coefficient'=>0,'x'=>15+$i*12,'y'=>35+$i*4];
$links=[];for($i=1;$i<=5;$i++){$from=$i===1?'source:1':'node:'.($i-1);$to='node:'.$i;$links[]=['id'=>$i,'key'=>'link:'.$i,'engine_id'=>'P'.$i,'route_name'=>'Pipa '.$i,'link_type'=>'PIPE','origin_key'=>$from,'destination_key'=>$to,'origin_engine_id'=>$nodes[$from]['engine_id'],'destination_engine_id'=>$nodes[$to]['engine_id'],'pipe_length_m'=>300,'pipe_diameter_mm'=>100,'roughness_coefficient'=>150,'minor_loss_coefficient'=>0,'planned_flow_lps'=>2,'max_pipe_capacity_lps'=>3,'pipe_type'=>'HDPE','check_valve'=>0,'initial_status'=>'OPEN','status'=>'aktif'];}
$demoModel=['project_id'=>999,'nodes'=>$nodes,'links'=>$links,'patterns'=>[],'curves'=>[]];$demoCatalog=[['id'=>11,'material'=>'HDPE','dn_mm'=>110,'outside_diameter_mm'=>110,'wall_thickness_mm'=>10,'inside_diameter_mm'=>90,'pressure_class'=>'PN16','allowable_pressure_bar'=>16,'hazen_williams_c'=>150,'darcy_roughness_mm'=>.0015,'price_per_meter'=>100000],['id'=>12,'material'=>'HDPE','dn_mm'=>160,'outside_diameter_mm'=>160,'wall_thickness_mm'=>14.6,'inside_diameter_mm'=>130.8,'pressure_class'=>'PN16','allowable_pressure_bar'=>16,'hazen_williams_c'=>150,'darcy_roughness_mm'=>.0015,'price_per_meter'=>180000]];$demoInputs=[];foreach($links as $link)$demoInputs[]=['network_link_id'=>$link['id'],'route_name'=>$link['route_name'],'pipe_length_m'=>300,'origin_key'=>$link['origin_key'],'destination_key'=>$link['destination_key'],'is_diameter_locked'=>0,'allowed_catalog_ids'=>[11,12],'minimum_dn_mm'=>100,'maximum_dn_mm'=>200];
$demo=$service->optimize($demoModel,['hydraulic_method'=>'H-W','optimization_goal'=>'LOWEST_INITIAL_COST','max_combinations'=>4,'max_iterations'=>4,'calculation_timeout_seconds'=>30],['minimum_pressure_m'=>5,'target_pressure_m'=>15,'maximum_pressure_m'=>100,'minimum_velocity_mps'=>.01,'maximum_velocity_mps'=>3,'minimum_velocity_active'=>1,'maximum_unit_headloss_active'=>1,'maximum_unit_headloss_m_per_km'=>100,'pressure_safety_factor'=>1],$demoInputs,$demoCatalog,[['code'=>'PEAK','name'=>'Puncak','scenario_type'=>'PEAK_HOUR','demand_multiplier'=>1,'source_head_adjustment_m'=>0,'fire_flow_lps'=>0,'is_required'=>1,'is_active'=>1]]);$assert($demo['tested_combinations']===4&&count($demo['alternatives'])===4,'Demo satu sumber, lima node, dan lima ruas diuji oleh EPANET');$recommended=count(array_filter($demo['alternatives'],fn($x)=>$x['is_recommended']));if($recommended!==1)echo json_encode(array_map(fn($x)=>[$x['status'],$x['failure_reasons']],$demo['alternatives']),JSON_UNESCAPED_UNICODE).PHP_EOL;$assert($recommended===1,'Demo menghasilkan tepat satu rekomendasi yang lolos');
exit($failed?1:0);
