<?php
$columns = array_keys($def['fields']);
if($module==='monitoring') $columns=['recorded_at','device_id','sensor_id','raw_value','calibrated_value','unit','quality_status','validation_status','source','signal_strength','battery_voltage'];
if($module==='alerts') $columns=['occurred_at','device_id','sensor_id','alert_type','value','priority','message','status'];
if($module==='activity-logs') $columns=['created_at','user_id','action','module','reference_id','ip_address'];
$labels=$def['fields'];
$optionSets=[
 'water-sources.source_type'=>['mata_air'=>'Mata Air','sumur_bor'=>'Sumur Bor','sungai'=>'Sungai','embung'=>'Embung','air_hujan'=>'Air Hujan','pdam'=>'PDAM','lainnya'=>'Sumber Alternatif Lainnya'],
 'water-sources.measurement_season'=>['kemarau'=>'Kemarau','normal'=>'Normal','hujan'=>'Hujan'],
 'water-sources.water_quality'=>['baik'=>'Baik','perlu_pengolahan'=>'Perlu Pengolahan','tidak_layak'=>'Tidak Layak'],
 'water-sources.status'=>['aktif'=>'Aktif','tidak_aktif'=>'Tidak Aktif','perawatan'=>'Perawatan'],
 'reservoirs.reservoir_type'=>['ground_reservoir'=>'Ground Reservoir','elevated_reservoir'=>'Elevated Reservoir','bak_penampung'=>'Bak Penampung','tangki_distribusi'=>'Tangki Distribusi'],
 'reservoirs.status'=>['aktif'=>'Aktif','tidak_aktif'=>'Tidak Aktif','perawatan'=>'Perawatan'],
 'service-areas.priority'=>['sangat_tinggi'=>'Sangat Tinggi','tinggi'=>'Tinggi','sedang'=>'Sedang','rendah'=>'Rendah'],
 'distribution-networks.origin_type'=>['source'=>'Sumber Air','reservoir'=>'Reservoir'],
 'distribution-networks.destination_type'=>['reservoir'=>'Reservoir','service_area'=>'Wilayah Layanan'],
 'distribution-networks.pump_status'=>['tanpa_pompa'=>'Tanpa Pompa','aktif'=>'Aktif','tidak_aktif'=>'Tidak Aktif'],
 'distribution-networks.status'=>['aktif'=>'Aktif','tidak_aktif'=>'Tidak Aktif','perawatan'=>'Perawatan'],
 'simulation-scenarios.season'=>['kemarau'=>'Kemarau','normal'=>'Normal','hujan'=>'Hujan','ekstrem'=>'Kemarau Ekstrem'],
 'simulation-scenarios.status'=>['draft'=>'Draft','aktif'=>'Aktif','selesai'=>'Selesai'],
];
?>
<?php if($module==='locations'):?><link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"><?php endif?>
<section class="page-head"><div><p class="eyebrow">Manajemen data</p><h2><?=e($def['title'])?></h2><p><?= $module==='devices' ? 'Hubungkan alat ke lokasi sumber air dan Google Sheet pembacaan sensornya.' : 'Kelola dan telusuri data dengan cepat.' ?></p></div><div class="d-flex gap-2"><?php if(empty($def['readonly'])):?><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#formModal"><i class="bi bi-plus-lg"></i> Tambah Data</button><?php endif?><button class="btn btn-outline-primary" data-export-table="#dataTable"><i class="bi bi-download"></i> CSV</button></div></section>
<div class="panel"><div class="table-toolbar"><form class="input-icon" method="get"><i class="bi bi-search"></i><input class="form-control" name="q" value="<?=e($_GET['q']??'')?>" placeholder="Cari data..."></form><span class="record-count"><?=count($rows)?> data ditampilkan</span></div>
<div class="table-responsive"><table class="table align-middle data-table mb-0" id="dataTable"><thead><tr><th>#</th><?php foreach($columns as $col):?><th><?=e($labels[$col]??ucwords(str_replace('_',' ',$col)))?></th><?php endforeach?><th>Aksi</th></tr></thead><tbody>
<?php if(!$rows):?><tr><td colspan="<?=count($columns)+2?>"><div class="empty-state"><i class="bi bi-inbox"></i><h4>Belum ada data</h4><p>Data akan tampil di sini setelah ditambahkan.</p></div></td></tr><?php endif?>
<?php foreach($rows as $i=>$row):?><tr><td><?=($i+1)?></td><?php foreach($columns as $col): $val=$row[$col]??null; ?><td><?php if(str_contains($col,'status')||in_array($col,['priority','is_active','is_public'],true)):?><span class="status-badge status-<?=e(strtolower(str_replace(' ','_',($val===1||$val==='1')?'aktif':(string)$val)))?>"><?=e(($val===1||$val==='1')?'Aktif':ucwords(str_replace('_',' ',(string)$val)))?></span><?php elseif(str_ends_with($col,'_id')):?><span class="text-secondary">#<?=e($val)?></span><?php elseif(is_string($val)&&strlen($val)>70):?><?=e(substr($val,0,70))?>…<?php else:?><?=e($val??'—')?><?php endif?></td><?php endforeach?><td><div class="table-actions"><?php if(empty($def['readonly'])):?><a class="icon-btn" href="<?=url($module.'/'.$row['id'])?>" title="Edit"><i class="bi bi-pencil"></i></a><?php if(has_role(['super_admin','administrator'])):?><form method="post" action="<?=url($module.'/'.$row['id'])?>" onsubmit="return confirm('Arsipkan data ini?')"><?=csrf_field()?><input type="hidden" name="_method" value="DELETE"><button class="icon-btn danger" title="Hapus"><i class="bi bi-trash"></i></button></form><?php endif; endif?></div></td></tr><?php endforeach?>
</tbody></table></div></div>
<?php if(empty($def['readonly'])):?><div class="modal fade" id="formModal" tabindex="-1"><div class="modal-dialog modal-lg modal-dialog-scrollable"><form class="modal-content" method="post" action="<?=url($module.($record?'/'.$record['id']:''))?>"><div class="modal-header"><div><p class="eyebrow mb-1"><?= $record?'Perbarui':'Data baru'?></p><h3 class="modal-title h5"><?=e($def['title'])?></h3></div><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><p class="required-note"><span>*</span> Wajib diisi</p><div class="row g-3"><?=csrf_field()?>
<?php if($module==='locations'):?><div class="col-12"><section class="location-picker-panel"><div class="location-picker-head"><div><h4><i class="bi bi-geo-alt-fill"></i> Pilih Titik dari Peta <span class="required-mark">*</span></h4><p>Klik posisi mata air pada peta. Latitude dan longitude akan terisi otomatis.</p></div><button class="btn btn-outline-primary btn-sm" type="button" id="useDeviceLocation"><i class="bi bi-crosshair"></i> Gunakan Lokasi Perangkat</button></div><div id="locationPickerMap" data-lat="<?=e($record['latitude']??'')?>" data-lng="<?=e($record['longitude']??'')?>" data-existing='<?=e(json_encode(array_values(array_filter(array_map(fn($item)=>['id'=>$item['id'],'name'=>$item['name'],'latitude'=>$item['latitude'],'longitude'=>$item['longitude']],$rows),fn($item)=>$item['latitude']!==null&&$item['longitude']!==null))))?>'></div><div class="location-picker-status" id="locationPickerStatus"><i class="bi bi-info-circle"></i> Belum ada titik dipilih.</div></section></div><?php endif?>
<?php if($module==='devices'):?><div class="col-12"><div class="alert alert-info mb-0"><i class="bi bi-google"></i> <strong>Data Google Sheet:</strong> isi URL spreadsheet, lalu masukkan GID tab data (angka setelah <code>gid=</code> pada URL). Sheet harus dibagikan sebagai <em>Siapa saja yang memiliki link dapat melihat</em>.</div></div><?php endif?>
<?php foreach($def['fields'] as $field=>$label): $value=$record[$field]??''; $lookupKey=$field==='location_id'?'locations':($field==='device_id'?'devices':($field==='sensor_id'?'sensors':null)); $isRequired=in_array($field,$def['required']??[],true); $fieldOptions=$optionSets[$module.'.'.$field]??null; ?>
<?php if(in_array($field,['is_active','is_public','show_on_home'],true)):?><div class="col-md-6"><div class="form-check form-switch mt-4"><input class="form-check-input" type="checkbox" name="<?=$field?>" id="<?=$field?>" <?=($record?($value?'checked':''):'checked')?>><label class="form-check-label" for="<?=$field?>"><?=e($label)?></label></div></div>
<?php elseif($fieldOptions):?><div class="col-md-6"><label class="form-label"><?=e($label)?><?php if($isRequired):?> <span class="required-mark">*</span><?php endif?></label><select class="form-select" name="<?=$field?>" <?=$isRequired?'required':''?>><option value="">Pilih...</option><?php foreach($fieldOptions as $optionValue=>$optionLabel):?><option value="<?=e($optionValue)?>" <?=((string)$value===(string)$optionValue)?'selected':''?>><?=e($optionLabel)?></option><?php endforeach?></select></div>
<?php elseif($lookupKey):?><div class="col-md-6"><label class="form-label"><?=e($label)?><?php if($isRequired):?> <span class="required-mark">*</span><?php endif?></label><select class="form-select" name="<?=$field?>" <?=$isRequired?'required':''?>><option value="">Pilih...</option><?php foreach($lookups[$lookupKey] as $option):?><option value="<?=$option['id']?>" <?=((string)$value===(string)$option['id'])?'selected':''?>><?=e($option['name'])?></option><?php endforeach?></select></div>
<?php elseif(in_array($field,['description','notes','content','summary','action_taken'],true)):?><div class="col-12"><label class="form-label"><?=e($label)?><?php if($isRequired):?> <span class="required-mark">*</span><?php endif?></label><textarea class="form-control" name="<?=$field?>" rows="3" <?=$isRequired?'required':''?>><?=e($value)?></textarea></div>
<?php elseif($module==='devices' && $field==='google_sheet_url'):?><div class="col-12"><label class="form-label"><?=e($label)?></label><input class="form-control" type="url" name="<?=$field?>" value="<?=e($value)?>" placeholder="https://docs.google.com/spreadsheets/d/.../edit?gid=..."><small class="form-text">Tempel URL Google Sheet yang sudah dapat dilihat oleh publik.</small></div>
<?php elseif($module==='devices' && $field==='google_sheet_gid'):?><div class="col-md-6"><label class="form-label"><?=e($label)?></label><input class="form-control" type="text" name="<?=$field?>" value="<?=e($value)?>" placeholder="Contoh: 565717997"><small class="form-text">Kosongkan bila memakai tab pertama (GID 0).</small></div>
<?php elseif($module==='devices' && $field==='google_sheet_name'):?><div class="col-md-6"><label class="form-label"><?=e($label)?></label><input class="form-control" type="text" name="<?=$field?>" value="<?=e($value)?>" placeholder="Contoh: Data Lokasi A"></div>
<?php else: $numericFields=['cost','latitude','longitude','elevation','elevation_m','normal_min','normal_max','warning_min','warning_max','danger_min','danger_max','calibration_factor','offset_value','decimal_places','send_interval_seconds','min_flow_lps','normal_flow_lps','max_flow_lps','current_sensor_flow_lps','source_loss_percent','length_m','width_m','height_m','geometric_volume_m3','effective_percent','effective_capacity_m3','minimum_operational_m3','initial_volume_m3','initial_water_level_m','max_inflow_lps','max_outflow_lps','loss_percent','population','house_connections','public_facilities','liters_per_person_day','public_facility_liters_day','max_day_factor','peak_hour_factor','network_loss_percent','service_hours_day','average_demand_lps','max_day_demand_lps','peak_hour_demand_lps','origin_id','destination_id','pipe_length_m','pipe_diameter_mm','start_elevation_m','end_elevation_m','elevation_difference_m','max_pipe_capacity_lps','planned_flow_lps','pump_capacity_lps','pump_hours','flow_priority','population_growth_percent','source_reduction_percent']; $type=(str_contains($field,'date')||str_ends_with($field,'_at'))?'date':(in_array($field,['email'],true)?'email':(in_array($field,$numericFields,true)?'number':'text')); $rangeAttr=$field==='latitude'?'min="-90" max="90" placeholder="Contoh: -3.998459" '.($module==='locations'?'readonly':''):($field==='longitude'?'min="-180" max="180" placeholder="Contoh: 122.526300" '.($module==='locations'?'readonly':''):'');?><div class="col-md-6"><label class="form-label"><?=e($label)?><?php if($isRequired):?> <span class="required-mark">*</span><?php endif?></label><input class="form-control" type="<?=$type?>" <?=($type==='number'?'step="any"':'')?> <?=$rangeAttr?> name="<?=$field?>" value="<?=e($value)?>" <?=$isRequired?'required':''?>><?php if(in_array($field,['latitude','longitude'],true)&&$module==='locations'):?><small class="form-text">Terisi otomatis setelah memilih titik pada peta.</small><?php endif?></div><?php endif?>
<?php endforeach?></div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Batal</button><button class="btn btn-primary"><i class="bi bi-check2"></i> Simpan</button></div></form></div></div>
<?php if($record):?><script>document.addEventListener('DOMContentLoaded',()=>bootstrap.Modal.getOrCreateInstance('#formModal').show())</script><?php endif; endif?>
<?php if($module==='locations'&&!empty($def['fields'])):?><script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script><script>
document.addEventListener('DOMContentLoaded',()=>{
 const mapEl=document.querySelector('#locationPickerMap'); if(!mapEl||!window.L)return;
 const latInput=document.querySelector('input[name="latitude"]'),lngInput=document.querySelector('input[name="longitude"]'),status=document.querySelector('#locationPickerStatus');
 const initialLat=parseFloat(mapEl.dataset.lat),initialLng=parseFloat(mapEl.dataset.lng),hasInitial=Number.isFinite(initialLat)&&Number.isFinite(initialLng);
 const map=L.map(mapEl,{scrollWheelZoom:true,wheelPxPerZoomLevel:60}).setView(hasInitial?[initialLat,initialLng]:[-4.0,122.5],hasInitial?15:8);
 addMapBaseLayers(map);
 let selectedMarker=null;
 const choose=(lat,lng,center=true)=>{lat=+lat.toFixed(7);lng=+lng.toFixed(7);latInput.value=lat;lngInput.value=lng;if(selectedMarker)selectedMarker.setLatLng([lat,lng]);else selectedMarker=L.marker([lat,lng],{draggable:true}).addTo(map);selectedMarker.off('dragend').on('dragend',e=>{const p=e.target.getLatLng();choose(p.lat,p.lng,false)});if(center)map.setView([lat,lng],Math.max(map.getZoom(),15));status.classList.add('selected');status.innerHTML=`<i class="bi bi-check-circle-fill"></i> Titik dipilih: ${lat}, ${lng}`};
 if(hasInitial)choose(initialLat,initialLng,false);
 const existing=JSON.parse(mapEl.dataset.existing||'[]');existing.forEach(item=>{if(hasInitial&&+item.id===<?=json_encode((int)($record['id']??0))?>)return;L.circleMarker([+item.latitude,+item.longitude],{radius:6,color:'#fff',weight:2,fillColor:'#64748b',fillOpacity:.85}).addTo(map).bindTooltip(item.name)});
 map.on('click',event=>choose(event.latlng.lat,event.latlng.lng));
 document.querySelector('#useDeviceLocation')?.addEventListener('click',()=>{if(!navigator.geolocation){status.innerHTML='<i class="bi bi-exclamation-circle"></i> Perangkat tidak mendukung lokasi.';return}status.innerHTML='<i class="bi bi-hourglass-split"></i> Mengambil lokasi perangkat…';navigator.geolocation.getCurrentPosition(pos=>choose(pos.coords.latitude,pos.coords.longitude),()=>status.innerHTML='<i class="bi bi-exclamation-circle"></i> Lokasi tidak dapat diakses. Izinkan akses lokasi pada browser.',{enableHighAccuracy:true,timeout:12000})});
 document.querySelector('#formModal')?.addEventListener('shown.bs.modal',()=>setTimeout(()=>map.invalidateSize(),120));
});
</script><?php endif?>
