<?php
declare(strict_types=1);

use App\Core\Database;
use App\Core\Env;

require_once dirname(__DIR__,2).'/app/Core/Env.php';
require_once dirname(__DIR__,2).'/app/Core/Database.php';
Env::load(dirname(__DIR__,2).'/.env');
$pdo=Database::connection();

$tables=[
"CREATE TABLE IF NOT EXISTS pipe_diameter_catalog (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 material VARCHAR(80) NOT NULL,
 dn_mm DECIMAL(12,3) NOT NULL,
 outside_diameter_mm DECIMAL(12,3) NOT NULL,
 wall_thickness_mm DECIMAL(12,3) NOT NULL,
 inside_diameter_mm DECIMAL(12,3) NOT NULL,
 pressure_class VARCHAR(40) NOT NULL,
 allowable_pressure_bar DECIMAL(12,4) NULL,
 hazen_williams_c DECIMAL(12,4) NULL,
 darcy_roughness_mm DECIMAL(12,6) NULL,
 price_per_meter DECIMAL(18,2) NULL,
 is_active TINYINT(1) NOT NULL DEFAULT 1,
 is_custom TINYINT(1) NOT NULL DEFAULT 0,
 description TEXT NULL,
 created_by BIGINT UNSIGNED NULL,
 created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
 updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 deleted_at DATETIME NULL,
 UNIQUE KEY uq_pipe_catalog(material,dn_mm,pressure_class),
 INDEX idx_pipe_catalog_filter(is_active,material,dn_mm)
) ENGINE=InnoDB",
"CREATE TABLE IF NOT EXISTS auto_design_analyses (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 project_id BIGINT UNSIGNED NOT NULL,
 analysis_number VARCHAR(80) NOT NULL,
 name VARCHAR(180) NOT NULL,
 location VARCHAR(200) NULL,
 planner_name VARCHAR(160) NULL,
 analysis_date DATE NOT NULL,
 notes TEXT NULL,
 unit_system ENUM('SI') NOT NULL DEFAULT 'SI',
 design_standard VARCHAR(180) NULL,
 hydraulic_method ENUM('H-W','D-W') NOT NULL DEFAULT 'H-W',
 design_mode ENUM('MANUAL_CHECK','AUTO_DESIGN') NOT NULL DEFAULT 'AUTO_DESIGN',
 optimization_goal ENUM('SMALLEST_DIAMETER','BALANCED','LOWEST_INITIAL_COST','LOWEST_HEADLOSS','TARGET_PRESSURE','TARGET_VELOCITY','LOWEST_LIFECYCLE_COST','MULTI_CRITERIA') NOT NULL DEFAULT 'LOWEST_INITIAL_COST',
 demand_method ENUM('DIRECT','POPULATION','HOUSE_CONNECTION','SERVICE_NODES','HOURLY_PATTERN','PROJECT_DATA') NOT NULL DEFAULT 'PROJECT_DATA',
 base_year INT NULL,
 design_year INT NULL,
 initial_population BIGINT NULL,
 population_growth_percent DECIMAL(10,4) NULL,
 population_projection_method ENUM('ARITHMETIC','GEOMETRIC','EXPONENTIAL','MANUAL') NULL,
 projected_population BIGINT NULL,
 domestic_lpd DECIMAL(16,4) NULL,
 non_domestic_percent DECIMAL(10,4) NULL,
 water_loss_percent DECIMAL(10,4) NULL,
 max_day_factor DECIMAL(10,4) NULL,
 peak_hour_factor DECIMAL(10,4) NULL,
 average_demand_lps DECIMAL(18,6) NULL,
 max_day_demand_lps DECIMAL(18,6) NULL,
 peak_hour_demand_lps DECIMAL(18,6) NULL,
 fire_flow_lps DECIMAL(18,6) NULL,
 final_design_flow_lps DECIMAL(18,6) NULL,
 hourly_pattern_json JSON NULL,
 source_name VARCHAR(180) NULL,
 source_type VARCHAR(80) NULL,
 source_energy_basis ENUM('WATER_LEVEL','TOTAL_HEAD') NOT NULL DEFAULT 'TOTAL_HEAD',
 source_min_level_m DECIMAL(14,4) NULL,
 source_normal_level_m DECIMAL(14,4) NULL,
 source_max_level_m DECIMAL(14,4) NULL,
 source_total_head_m DECIMAL(14,4) NULL,
 source_available_flow_lps DECIMAL(18,6) NULL,
 source_service_hours DECIMAL(8,3) NULL,
 source_supply_mode ENUM('GRAVITY','PUMP') NOT NULL DEFAULT 'GRAVITY',
 reservoir_type VARCHAR(80) NULL,
 reservoir_base_elevation_m DECIMAL(14,4) NULL,
 reservoir_min_level_m DECIMAL(14,4) NULL,
 reservoir_normal_level_m DECIMAL(14,4) NULL,
 reservoir_max_level_m DECIMAL(14,4) NULL,
 reservoir_effective_height_m DECIMAL(14,4) NULL,
 reservoir_freeboard_m DECIMAL(14,4) NULL,
 reservoir_shape ENUM('RECTANGLE','SQUARE','CYLINDER','CUSTOM') NOT NULL DEFAULT 'RECTANGLE',
 reservoir_compartments INT NOT NULL DEFAULT 1,
 reservoir_method ENUM('DAILY_PERCENT','MASS_CURVE','DETENTION_TIME') NOT NULL DEFAULT 'DAILY_PERCENT',
 reservoir_operating_hours DECIMAL(10,3) NULL,
 reservoir_storage_percent DECIMAL(10,4) NULL,
 reservoir_reserve_percent DECIMAL(10,4) NULL,
 reservoir_fire_volume_m3 DECIMAL(18,4) NULL,
 reservoir_emergency_volume_m3 DECIMAL(18,4) NULL,
 reservoir_dead_volume_m3 DECIMAL(18,4) NULL,
 reservoir_operational_volume_m3 DECIMAL(18,4) NULL,
 reservoir_total_required_m3 DECIMAL(18,4) NULL,
 reservoir_range_json JSON NULL,
 optimization_weights_json JSON NULL,
 max_alternatives INT NOT NULL DEFAULT 10,
 max_iterations INT NOT NULL DEFAULT 100,
 max_combinations INT NOT NULL DEFAULT 500,
 calculation_timeout_seconds INT NOT NULL DEFAULT 120,
 selected_alternative_id BIGINT UNSIGNED NULL,
 selected_reservoir_alternative_id BIGINT UNSIGNED NULL,
 engine_version VARCHAR(80) NOT NULL DEFAULT 'SIMMA-AUTO-1.0 / EPANET-2.3.5',
 status ENUM('DRAFT','READY','RUNNING','COMPLETED','FAILED') NOT NULL DEFAULT 'DRAFT',
 last_error TEXT NULL,
 created_by BIGINT UNSIGNED NULL,
 created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
 updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 deleted_at DATETIME NULL,
 UNIQUE KEY uq_auto_design_number(project_id,analysis_number),
 INDEX idx_auto_design_project(project_id,status,deleted_at)
) ENGINE=InnoDB",
"CREATE TABLE IF NOT EXISTS auto_design_criteria (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 analysis_id BIGINT UNSIGNED NOT NULL,
 criterion_key VARCHAR(100) NOT NULL,
 criterion_label VARCHAR(180) NOT NULL,
 numeric_value DECIMAL(20,8) NULL,
 text_value VARCHAR(255) NULL,
 unit VARCHAR(40) NULL,
 is_active TINYINT(1) NOT NULL DEFAULT 1,
 standard_source VARCHAR(255) NULL,
 explanation VARCHAR(500) NULL,
 created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
 updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 UNIQUE KEY uq_design_criterion(analysis_id,criterion_key),
 INDEX idx_design_criterion(analysis_id,is_active)
) ENGINE=InnoDB",
"CREATE TABLE IF NOT EXISTS auto_design_pipe_inputs (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 analysis_id BIGINT UNSIGNED NOT NULL,
 network_link_id BIGINT UNSIGNED NOT NULL,
 demand_along_lps DECIMAL(18,6) NOT NULL DEFAULT 0,
 is_diameter_locked TINYINT(1) NOT NULL DEFAULT 0,
 fixed_catalog_id BIGINT UNSIGNED NULL,
 minimum_dn_mm DECIMAL(12,3) NULL,
 maximum_dn_mm DECIMAL(12,3) NULL,
 allowed_catalog_ids_json JSON NULL,
 diameter_group VARCHAR(80) NULL,
 fitting_count INT NOT NULL DEFAULT 0,
 minor_loss_coefficient DECIMAL(14,6) NOT NULL DEFAULT 0,
 transient_enabled TINYINT(1) NOT NULL DEFAULT 0,
 wave_speed_mps DECIMAL(14,4) NULL,
 velocity_change_mps DECIMAL(14,4) NULL,
 valve_closure_seconds DECIMAL(14,4) NULL,
 pressure_allowance_bar DECIMAL(14,4) NULL,
 created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
 updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 UNIQUE KEY uq_design_pipe_input(analysis_id,network_link_id),
 INDEX idx_design_pipe_analysis(analysis_id)
) ENGINE=InnoDB",
"CREATE TABLE IF NOT EXISTS auto_design_scenarios (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 analysis_id BIGINT UNSIGNED NOT NULL,
 code VARCHAR(80) NOT NULL,
 name VARCHAR(160) NOT NULL,
 scenario_type VARCHAR(60) NOT NULL,
 demand_multiplier DECIMAL(12,6) NOT NULL DEFAULT 1,
 source_head_adjustment_m DECIMAL(14,4) NOT NULL DEFAULT 0,
 fire_flow_lps DECIMAL(18,6) NOT NULL DEFAULT 0,
 outage_link_id BIGINT UNSIGNED NULL,
 pump_state ENUM('UNCHANGED','ON','OFF') NOT NULL DEFAULT 'UNCHANGED',
 is_required TINYINT(1) NOT NULL DEFAULT 1,
 is_active TINYINT(1) NOT NULL DEFAULT 1,
 created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
 updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 UNIQUE KEY uq_design_scenario(analysis_id,code)
) ENGINE=InnoDB",
"CREATE TABLE IF NOT EXISTS auto_design_alternatives (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 analysis_id BIGINT UNSIGNED NOT NULL,
 rank_number INT NULL,
 combination_code VARCHAR(120) NOT NULL,
 total_cost DECIMAL(20,2) NULL,
 lifecycle_cost DECIMAL(20,2) NULL,
 minimum_pressure_m DECIMAL(16,6) NULL,
 maximum_pressure_m DECIMAL(16,6) NULL,
 minimum_velocity_mps DECIMAL(16,6) NULL,
 maximum_velocity_mps DECIMAL(16,6) NULL,
 total_headloss_m DECIMAL(18,6) NULL,
 technical_score DECIMAL(16,8) NULL,
 final_score DECIMAL(16,8) NULL,
 status ENUM('PASS','WARNING','FAIL','NOT_CALCULATED') NOT NULL DEFAULT 'NOT_CALCULATED',
 failure_reasons TEXT NULL,
 is_recommended TINYINT(1) NOT NULL DEFAULT 0,
 is_selected TINYINT(1) NOT NULL DEFAULT 0,
 converged TINYINT(1) NOT NULL DEFAULT 0,
 calculation_seconds DECIMAL(14,4) NULL,
 scenario_summary_json JSON NULL,
 created_by BIGINT UNSIGNED NULL,
 created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
 UNIQUE KEY uq_design_combination(analysis_id,combination_code),
 INDEX idx_design_alt_rank(analysis_id,status,rank_number)
) ENGINE=InnoDB",
"CREATE TABLE IF NOT EXISTS auto_design_alternative_pipes (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 alternative_id BIGINT UNSIGNED NOT NULL,
 scenario_code VARCHAR(80) NOT NULL,
 network_link_id BIGINT UNSIGNED NOT NULL,
 catalog_id BIGINT UNSIGNED NULL,
 material VARCHAR(80) NULL,
 dn_mm DECIMAL(12,3) NULL,
 outside_diameter_mm DECIMAL(12,3) NULL,
 wall_thickness_mm DECIMAL(12,3) NULL,
 inside_diameter_mm DECIMAL(12,3) NOT NULL,
 pressure_class VARCHAR(40) NULL,
 allowable_pressure_bar DECIMAL(14,4) NULL,
 flow_lps DECIMAL(18,6) NULL,
 velocity_mps DECIMAL(18,8) NULL,
 reynolds_number DECIMAL(22,4) NULL,
 friction_factor DECIMAL(18,10) NULL,
 major_headloss_m DECIMAL(18,8) NULL,
 minor_headloss_m DECIMAL(18,8) NULL,
 unit_headloss_m_per_km DECIMAL(18,8) NULL,
 start_pressure_m DECIMAL(18,8) NULL,
 end_pressure_m DECIMAL(18,8) NULL,
 design_pressure_bar DECIMAL(18,8) NULL,
 cost DECIMAL(20,2) NULL,
 status VARCHAR(60) NOT NULL,
 failure_reason VARCHAR(500) NULL,
 INDEX idx_alt_pipe(alternative_id,scenario_code,network_link_id)
) ENGINE=InnoDB",
"CREATE TABLE IF NOT EXISTS auto_design_alternative_nodes (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 alternative_id BIGINT UNSIGNED NOT NULL,
 scenario_code VARCHAR(80) NOT NULL,
 node_key VARCHAR(120) NOT NULL,
 node_name VARCHAR(180) NOT NULL,
 elevation_m DECIMAL(18,8) NULL,
 demand_lps DECIMAL(18,8) NULL,
 hydraulic_head_m DECIMAL(18,8) NULL,
 pressure_m DECIMAL(18,8) NULL,
 pressure_kpa DECIMAL(18,8) NULL,
 pressure_bar DECIMAL(18,8) NULL,
 status VARCHAR(60) NOT NULL,
 INDEX idx_alt_node(alternative_id,scenario_code,node_key)
) ENGINE=InnoDB",
"CREATE TABLE IF NOT EXISTS auto_design_reservoir_alternatives (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 analysis_id BIGINT UNSIGNED NOT NULL,
 rank_number INT NULL,
 shape ENUM('RECTANGLE','SQUARE','CYLINDER','CUSTOM') NOT NULL,
 length_or_diameter_m DECIMAL(14,4) NULL,
 width_m DECIMAL(14,4) NULL,
 effective_height_m DECIMAL(14,4) NOT NULL,
 freeboard_m DECIMAL(14,4) NOT NULL,
 construction_height_m DECIMAL(14,4) NOT NULL,
 compartments INT NOT NULL DEFAULT 1,
 effective_volume_m3 DECIMAL(18,6) NOT NULL,
 total_volume_m3 DECIMAL(18,6) NOT NULL,
 excess_volume_m3 DECIMAL(18,6) NOT NULL,
 footprint_m2 DECIMAL(18,6) NULL,
 status ENUM('PASS','WARNING','FAIL') NOT NULL,
 selection_reason VARCHAR(500) NULL,
 is_recommended TINYINT(1) NOT NULL DEFAULT 0,
 is_selected TINYINT(1) NOT NULL DEFAULT 0,
 created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
 INDEX idx_reservoir_alt(analysis_id,status,rank_number)
) ENGINE=InnoDB"
];
foreach($tables as $sql)$pdo->exec($sql);
$goalColumn=$pdo->query("SHOW COLUMNS FROM auto_design_analyses LIKE 'optimization_goal'")->fetch();
if($goalColumn&&!str_contains((string)$goalColumn['Type'],"'BALANCED'"))$pdo->exec("ALTER TABLE auto_design_analyses MODIFY optimization_goal ENUM('SMALLEST_DIAMETER','BALANCED','LOWEST_INITIAL_COST','LOWEST_HEADLOSS','TARGET_PRESSURE','TARGET_VELOCITY','LOWEST_LIFECYCLE_COST','MULTI_CRITERIA') NOT NULL DEFAULT 'LOWEST_INITIAL_COST'");

$catalog=[
 ['HDPE',63,63,5.8,51.4,'PN10',10,150,.0015,95000],['HDPE',75,75,6.8,61.4,'PN10',10,150,.0015,125000],
 ['HDPE',90,90,8.2,73.6,'PN10',10,150,.0015,175000],['HDPE',110,110,10,90,'PN10',10,150,.0015,245000],
 ['HDPE',160,160,14.6,130.8,'PN10',10,150,.0015,485000],['HDPE',200,200,18.2,163.6,'PN10',10,150,.0015,720000],
 ['uPVC',90,90,4.3,81.4,'PN10',10,150,.0015,135000],['uPVC',110,110,5.3,99.4,'PN10',10,150,.0015,190000],
 ['uPVC',160,160,7.7,144.6,'PN10',10,150,.0015,390000],['uPVC',200,200,9.6,180.8,'PN10',10,150,.0015,590000],
 ['PVC',250,250,11.9,226.2,'PN10',10,150,.0015,910000],['PVC',315,315,15,285,'PN10',10,150,.0015,1450000],
 ['Ductile Iron',100,118,7.2,103.6,'K9/PN16',16,130,.26,780000],['Ductile Iron',150,170,7.8,154.4,'K9/PN16',16,130,.26,1180000],
 ['Ductile Iron',200,222,8.4,205.2,'K9/PN16',16,130,.26,1710000],['Steel',100,114.3,4.5,105.3,'PN16',16,130,.045,640000],
 ['Steel',150,168.3,5,158.3,'PN16',16,130,.045,980000],['Steel',200,219.1,6,207.1,'PN16',16,130,.045,1490000],
 ['Galvanis',50,60.3,3.65,53,'Medium',8,120,.15,185000],['Galvanis',80,88.9,4.05,80.8,'Medium',8,120,.15,315000]
];
$insert=$pdo->prepare("INSERT IGNORE INTO pipe_diameter_catalog(material,dn_mm,outside_diameter_mm,wall_thickness_mm,inside_diameter_mm,pressure_class,allowable_pressure_bar,hazen_williams_c,darcy_roughness_mm,price_per_meter,is_active,is_custom,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,1,0,NOW(),NOW())");
foreach($catalog as $row)$insert->execute($row);
echo "Automatic design migration complete. Catalog rows: ".count($catalog).PHP_EOL;
