<?php $fmt=fn($v,$d=2)=>$v===null?'—':number_format((float)$v,$d,',','.'); ?>
<div class="d-flex justify-content-between align-items-center mb-3 no-print"><div><h2 class="h4 mb-1">Laporan Desain Otomatis</h2><small><?=e($analysis['analysis_number'].' · '.$analysis['name'])?></small></div><div class="d-flex gap-2"><a class="btn btn-outline-secondary" href="<?=url('automatic-design?project_id='.$analysis['project_id'].'&analysis_id='.$analysis['id'])?>">Kembali</a><button class="btn btn-primary" onclick="window.print()"><i class="bi bi-printer"></i> Cetak / PDF</button></div></div>
<article class="design-report">
 <header><div><span class="report-logo"><i class="bi bi-droplet-half"></i></span><div><small>SIMMA · MODUL PERENCANAAN</small><h1>Desain Otomatis Pipa dan Reservoir</h1><p>Perhitungan hidraulika terintegrasi EPANET 2.3.5</p></div></div><span class="badge text-bg-<?=$analysis['status']==='COMPLETED'?'success':'warning'?>"><?=$analysis['status']?></span></header>
 <section class="report-grid"><div><small>Nomor analisis</small><strong><?=e($analysis['analysis_number'])?></strong></div><div><small>Proyek</small><strong><?=e($analysis['project_code'].' — '.$analysis['project_name'])?></strong></div><div><small>Lokasi</small><strong><?=e($analysis['location']?:'—')?></strong></div><div><small>Perencana</small><strong><?=e($analysis['planner_name']?:'—')?></strong></div><div><small>Tanggal</small><strong><?=e($analysis['analysis_date'])?></strong></div><div><small>Metode</small><strong><?=e($analysis['hydraulic_method'].' / '.$analysis['optimization_goal'])?></strong></div></section>
 <h2>1. Ringkasan kebutuhan dan reservoir</h2><section class="report-metrics"><div><small>Debit rata-rata</small><strong><?=$fmt($analysis['average_demand_lps'],3)?> L/s</strong></div><div><small>Hari maksimum</small><strong><?=$fmt($analysis['max_day_demand_lps'],3)?> L/s</strong></div><div><small>Jam puncak</small><strong><?=$fmt($analysis['peak_hour_demand_lps'],3)?> L/s</strong></div><div><small>Debit desain final</small><strong><?=$fmt($analysis['final_design_flow_lps'],3)?> L/s</strong></div><div><small>Volume diperlukan</small><strong><?=$fmt($analysis['reservoir_total_required_m3'])?> m³</strong></div></section>
 <?php if($reservoir):?><p class="report-recommendation"><i class="bi bi-check-circle-fill"></i> Dimensi reservoir terpilih/rekomendasi: <strong><?=e($reservoir['shape'])?>, <?=$fmt($reservoir['length_or_diameter_m'])?> × <?=$fmt($reservoir['width_m'])?> × <?=$fmt($reservoir['effective_height_m'])?> m</strong>, freeboard <?=$fmt($reservoir['freeboard_m'])?> m, <?=$reservoir['compartments']?> kompartemen, volume efektif <?=$fmt($reservoir['effective_volume_m3'])?> m³.</p><?php endif?>
 <h2>2. Kriteria desain</h2><table><thead><tr><th>Kriteria</th><th>Nilai</th><th>Satuan</th></tr></thead><tbody><?php foreach($criteria as $key=>$value):?><tr><td><?=e(str_replace('_',' ',ucwords($key,'_')))?></td><td><?=$fmt($value,4)?></td><td><?=str_contains($key,'velocity')?'m/s':(str_contains($key,'pressure')?'m':(str_contains($key,'headloss')?'m/km':'-'))?></td></tr><?php endforeach?></tbody></table>
 <h2>3. Sumber, metode, dan skenario</h2><section class="report-grid"><div><small>Sumber</small><strong><?=e($analysis['source_name']?:'Mengikuti jaringan proyek')?></strong></div><div><small>Basis energi</small><strong><?=e($analysis['source_energy_basis'])?>: <?=$fmt($analysis['source_energy_basis']==='WATER_LEVEL'?$analysis['source_normal_level_m']:$analysis['source_total_head_m'])?> m</strong></div><div><small>Suplai</small><strong><?=e($analysis['source_supply_mode'])?> · <?=$fmt($analysis['source_available_flow_lps'])?> L/s</strong></div></section><table><thead><tr><th>Kode</th><th>Skenario</th><th>Jenis</th><th>Faktor demand</th><th>Δ head sumber</th><th>Kebakaran</th><th>Wajib</th></tr></thead><tbody><?php foreach($scenarios as $s):?><tr><td><?=e($s['code'])?></td><td><?=e($s['name'])?></td><td><?=e($s['scenario_type'])?></td><td><?=$fmt($s['demand_multiplier'],3)?></td><td><?=$fmt($s['source_head_adjustment_m'])?> m</td><td><?=$fmt($s['fire_flow_lps'])?> L/s</td><td><?=$s['is_required']?'Ya':'Tidak'?></td></tr><?php endforeach?></tbody></table>
 <div class="report-formulas"><strong>Rumus utama:</strong> A = πD²/4; V = Q/A; Hazen–Williams hf = 10,67·L·Q<sup>1,852</sup>/(C<sup>1,852</sup>·D<sup>4,87</sup>); Darcy–Weisbach hf = f·(L/D)·V²/(2g); hm = K·V²/(2g); pressure head = hydraulic head − elevasi. D adalah diameter dalam dan perhitungan memakai satuan SI.</div>
 <h2>4. Alternatif pipa terpilih</h2><?php if(!$alternative):?><p>Belum ada alternatif terpilih atau rekomendasi yang dapat dilaporkan.</p><?php else:?><section class="report-metrics"><div><small>Kode</small><strong><?=e($alternative['combination_code'])?></strong></div><div><small>Status</small><strong><?=e($alternative['status'])?></strong></div><div><small>Estimasi biaya pipa</small><strong>Rp <?=number_format((float)$alternative['total_cost'],0,',','.')?></strong></div><div><small>Tekanan minimum</small><strong><?=$fmt($alternative['minimum_pressure_m'])?> m</strong></div><div><small>Kecepatan maksimum</small><strong><?=$fmt($alternative['maximum_velocity_mps'])?> m/s</strong></div></section>
 <table><thead><tr><th>Skenario</th><th>Ruas</th><th>Material / DN / ID</th><th>Kelas</th><th>Q</th><th>V</th><th>Re</th><th>f</th><th>hf mayor</th><th>hf minor</th><th>m/km</th><th>P awal–akhir</th><th>Status</th></tr></thead><tbody><?php foreach($pipes as $p):?><tr><td><?=e($p['scenario_code'])?></td><td><?=e($p['route_name']??('Ruas '.$p['network_link_id']))?></td><td><?=e(($p['material']??'—').' / DN '.($p['dn_mm']??'—').' / ID '.($p['inside_diameter_mm']??'—').' mm')?></td><td><?=e($p['pressure_class']??'—')?></td><td><?=$fmt($p['flow_lps'],3)?> L/s</td><td><?=$fmt($p['velocity_mps'],3)?> m/s</td><td><?=$fmt($p['reynolds_number'],0)?></td><td><?=$fmt($p['friction_factor'],5)?></td><td><?=$fmt($p['major_headloss_m'],3)?> m</td><td><?=$fmt($p['minor_headloss_m'],3)?> m</td><td><?=$fmt($p['unit_headloss_m_per_km'],3)?></td><td><?=$fmt($p['start_pressure_m'])?>–<?=$fmt($p['end_pressure_m'])?> m</td><td><?=e($p['status'])?></td></tr><?php endforeach?></tbody></table>
 <h2>5. Hasil node</h2><table><thead><tr><th>Skenario</th><th>Node</th><th>Elevasi</th><th>Demand</th><th>Head</th><th>Tekanan (m)</th><th>kPa</th><th>bar</th><th>Status</th></tr></thead><tbody><?php foreach($nodes as $n):?><tr><td><?=e($n['scenario_code'])?></td><td><?=e($n['node_name'])?></td><td><?=$fmt($n['elevation_m'])?></td><td><?=$fmt($n['demand_lps'],3)?></td><td><?=$fmt($n['hydraulic_head_m'])?></td><td><?=$fmt($n['pressure_m'])?></td><td><?=$fmt($n['pressure_kpa'])?></td><td><?=$fmt($n['pressure_bar'],3)?></td><td><?=e($n['status'])?></td></tr><?php endforeach?></tbody></table><?php endif?>
 <h2>6. Perbandingan alternatif</h2><table><thead><tr><th>Rank</th><th>Kombinasi</th><th>Biaya</th><th>P min–maks</th><th>V min–maks</th><th>Headloss</th><th>Status</th></tr></thead><tbody><?php foreach($alternatives as $alt):?><tr><td><?=$alt['rank_number']?></td><td><?=e($alt['combination_code'])?> <?=$alt['is_recommended']?'(rekomendasi)':''?></td><td>Rp <?=number_format((float)$alt['total_cost'],0,',','.')?></td><td><?=$fmt($alt['minimum_pressure_m'])?>–<?=$fmt($alt['maximum_pressure_m'])?> m</td><td><?=$fmt($alt['minimum_velocity_mps'])?>–<?=$fmt($alt['maximum_velocity_mps'])?> m/s</td><td><?=$fmt($alt['total_headloss_m'])?> m</td><td><?=e($alt['status'])?></td></tr><?php endforeach?></tbody></table>
 <footer><p><strong>Batas penggunaan:</strong> hasil bergantung pada ketepatan geometri, elevasi, demand, karakteristik pipa, sumber, dan skenario. Verifikasi lapangan, transien, struktur, geoteknik, dan persetujuan tenaga ahli tetap diperlukan.</p><p>Mesin: <?=e($analysis['engine_version'])?> · Dicetak <?=date('d/m/Y H:i')?> WITA</p></footer>
</article>
