<?php
$a=$analysis??[];$val=fn(string $key,mixed $default='')=>$a[$key]??$default;$range=json_decode((string)($a['reservoir_range_json']??'{}'),true)?:[];
$weights=json_decode((string)($a['optimization_weights_json']??'{}'),true)?:['cost'=>35,'pressure'=>20,'velocity'=>15,'headloss'=>15,'safety'=>10,'uniformity'=>5];
$catalogActive=array_values(array_filter($catalog,fn($row)=>(int)$row['is_active']===1));
$statusClass=fn($s)=>match($s){'COMPLETED','PASS'=>'success','RUNNING','WARNING'=>'warning','FAILED','FAIL'=>'danger',default=>'secondary'};
?>
<section class="auto-design-hero">
  <div><span class="eyebrow">PERENCANAAN HIDRAULIKA TERINTEGRASI EPANET</span><h2>Desain Otomatis Pipa dan Reservoir</h2><p>Hitung kebutuhan, uji ukuran diameter dalam yang nyata, validasi semua skenario, dan simpan alternatif terpilih.</p></div>
  <div class="d-flex gap-2 flex-wrap"><a class="btn btn-outline-primary" href="<?=url('distribution-networks?project_id='.$projectId)?>"><i class="bi bi-diagram-3"></i> Buka Diagram</a><?php if($a):?><a class="btn btn-outline-dark" href="<?=url('automatic-design/report/'.$a['id'])?>"><i class="bi bi-printer"></i> Laporan</a><?php endif?></div>
</section>
<div class="alert alert-warning py-2"><i class="bi bi-exclamation-triangle me-2"></i><strong>Catatan teknis:</strong> hasil merupakan bantuan perencanaan. Kriteria, data lapangan, kelas tekanan, transien, dan desain final wajib diverifikasi tenaga ahli.</div>

<section class="card border-0 shadow-sm mb-3"><div class="card-body d-flex gap-3 align-items-end flex-wrap">
  <div class="flex-grow-1"><label class="form-label">Proyek jaringan <span class="required-mark">*</span></label><select class="form-select" onchange="location.href='<?=url('automatic-design')?>?project_id='+this.value"><option value="">Pilih proyek</option><?php foreach($projects as $p):?><option value="<?=$p['id']?>" <?=$projectId==(int)$p['id']?'selected':''?>><?=e($p['code'].' — '.$p['name'])?></option><?php endforeach?></select></div>
  <div class="flex-grow-1"><label class="form-label">Dokumen analisis</label><select class="form-select" onchange="if(this.value)location.href='<?=url('automatic-design')?>?project_id=<?=$projectId?>&analysis_id='+this.value"><option value="">Buat analisis baru</option><?php foreach($analyses as $row):?><option value="<?=$row['id']?>" <?=($a['id']??0)==$row['id']?'selected':''?>><?=e($row['analysis_number'].' — '.$row['name'])?></option><?php endforeach?></select></div>
  <?php if($a):?><span class="badge text-bg-<?=$statusClass($a['status'])?> fs-6 mb-1"><?=e($a['status'])?></span><?php endif?>
</div></section>

<form method="post" action="<?=url('automatic-design/save')?>" id="automaticDesignForm">
<?=csrf_field()?><input type="hidden" name="analysis_id" value="<?=e($a['id']??0)?>"><input type="hidden" name="project_id" value="<?=e($projectId)?>">
<ul class="nav nav-pills auto-design-tabs mb-3" role="tablist">
<?php foreach([['identity','1. Identitas','file-text'],['demand','2. Kebutuhan','people'],['source','3. Sumber & Reservoir','droplet-half'],['criteria','4. Kriteria','sliders'],['pipes','5. Kandidat Pipa','bezier2'],['scenarios','6. Skenario','layers'],['results','7. Hasil','bar-chart']] as $i=>$tab):?><li class="nav-item"><button class="nav-link <?=$i===0?'active':''?>" data-bs-toggle="pill" data-bs-target="#tab-<?=$tab[0]?>" type="button"><i class="bi bi-<?=$tab[2]?>"></i> <?=$tab[1]?></button></li><?php endforeach?>
</ul>
<div class="tab-content">
<div class="tab-pane fade show active" id="tab-identity"><section class="design-card"><header><div><span>LANGKAH 1</span><h3>Identitas dan metode desain</h3></div></header><div class="row g-3">
  <div class="col-md-3"><label class="form-label">Nomor analisis <span class="required-mark">*</span></label><input class="form-control" required name="analysis_number" value="<?=e($val('analysis_number','AUTO-'.date('Ymd-His')))?>"></div>
  <div class="col-md-5"><label class="form-label">Nama analisis <span class="required-mark">*</span></label><input class="form-control" required name="name" value="<?=e($val('name'))?>" placeholder="Desain SPAM Tahap I"></div>
  <div class="col-md-2"><label class="form-label">Tanggal <span class="required-mark">*</span></label><input class="form-control" required type="date" name="analysis_date" value="<?=e($val('analysis_date',date('Y-m-d')))?>"></div>
  <div class="col-md-2"><label class="form-label">Satuan</label><input class="form-control" value="SI" readonly></div>
  <div class="col-md-4"><label class="form-label">Lokasi</label><input class="form-control" name="location" value="<?=e($val('location'))?>"></div><div class="col-md-4"><label class="form-label">Perencana</label><input class="form-control" name="planner_name" value="<?=e($val('planner_name',user()['name']??''))?>"></div><div class="col-md-4"><label class="form-label">Standar/acuan</label><input class="form-control" name="design_standard" value="<?=e($val('design_standard','Kriteria proyek — verifikasi tenaga ahli'))?>"></div>
  <div class="col-md-3"><label class="form-label">Mode <span class="required-mark">*</span></label><select class="form-select" name="design_mode"><option value="AUTO_DESIGN" <?=$val('design_mode','AUTO_DESIGN')==='AUTO_DESIGN'?'selected':''?>>Desain otomatis</option><option value="MANUAL_CHECK" <?=$val('design_mode')==='MANUAL_CHECK'?'selected':''?>>Cek manual</option></select></div>
  <div class="col-md-3"><label class="form-label">Rumus kehilangan <span class="required-mark">*</span></label><select class="form-select" name="hydraulic_method"><option value="H-W" <?=$val('hydraulic_method','H-W')==='H-W'?'selected':''?>>Hazen–Williams</option><option value="D-W" <?=$val('hydraulic_method')==='D-W'?'selected':''?>>Darcy–Weisbach</option></select></div>
  <div class="col-md-6"><label class="form-label">Tujuan optimasi <span class="required-mark">*</span></label><select class="form-select" name="optimization_goal"><?php foreach(['LOWEST_INITIAL_COST'=>'Biaya awal terendah','SMALLEST_DIAMETER'=>'Diameter terkecil yang lolos','BALANCED'=>'Desain seimbang · semua patokan','LOWEST_HEADLOSS'=>'Headloss terendah','TARGET_PRESSURE'=>'Mendekati tekanan target','TARGET_VELOCITY'=>'Mendekati kecepatan target','LOWEST_LIFECYCLE_COST'=>'Biaya siklus hidup terendah','MULTI_CRITERIA'=>'Multi-kriteria'] as $k=>$label):?><option value="<?=$k?>" <?=$val('optimization_goal','LOWEST_INITIAL_COST')===$k?'selected':''?>><?=$label?></option><?php endforeach?></select></div>
  <div class="col-12"><label class="form-label">Catatan</label><textarea class="form-control" name="notes" rows="2"><?=e($val('notes'))?></textarea></div>
</div></section></div>

<div class="tab-pane fade" id="tab-demand"><section class="design-card"><header><div><span>LANGKAH 2</span><h3>Proyeksi dan kebutuhan air</h3></div></header><div class="row g-3">
  <div class="col-md-4"><label class="form-label">Metode kebutuhan <span class="required-mark">*</span></label><select name="demand_method" class="form-select"><option value="PROJECT_DATA">Data node proyek</option><option value="POPULATION" <?=$val('demand_method')==='POPULATION'?'selected':''?>>Proyeksi penduduk</option><option value="DIRECT" <?=$val('demand_method')==='DIRECT'?'selected':''?>>Debit langsung</option><option value="HOURLY_PATTERN" <?=$val('demand_method')==='HOURLY_PATTERN'?'selected':''?>>Pola 24 jam</option></select></div>
  <div class="col-md-2"><label class="form-label">Tahun dasar</label><input class="form-control" type="number" name="base_year" value="<?=e($val('base_year',date('Y')))?>"></div><div class="col-md-2"><label class="form-label">Tahun rencana</label><input class="form-control" type="number" name="design_year" value="<?=e($val('design_year',date('Y')+10))?>"></div>
  <div class="col-md-2"><label class="form-label">Penduduk awal</label><input class="form-control" type="number" min="0" name="initial_population" value="<?=e($val('initial_population',0))?>"></div><div class="col-md-2"><label class="form-label">Pertumbuhan (%/th)</label><input class="form-control" type="number" step="any" name="population_growth_percent" value="<?=e($val('population_growth_percent',1.5))?>"></div>
  <div class="col-md-3"><label class="form-label">Proyeksi</label><select name="population_projection_method" class="form-select"><?php foreach(['ARITHMETIC'=>'Aritmetika','GEOMETRIC'=>'Geometrik','EXPONENTIAL'=>'Eksponensial','MANUAL'=>'Manual'] as $k=>$l):?><option value="<?=$k?>" <?=$val('population_projection_method','GEOMETRIC')===$k?'selected':''?>><?=$l?></option><?php endforeach?></select></div>
  <div class="col-md-3"><label class="form-label">Penduduk rencana manual</label><input class="form-control" type="number" min="0" name="projected_population" value="<?=e($val('projected_population',0))?>"></div><div class="col-md-3"><label class="form-label">Konsumsi domestik (L/orang/hari)</label><input class="form-control" type="number" step="any" min="0" name="domestic_lpd" value="<?=e($val('domestic_lpd',120))?>"></div><div class="col-md-3"><label class="form-label">Debit langsung (L/s)</label><input class="form-control" type="number" step="any" min="0" name="direct_design_flow_lps" value="<?=e($val('final_design_flow_lps',0))?>"></div>
  <div class="col-md-3"><label class="form-label">Non-domestik (%)</label><input class="form-control" type="number" step="any" name="non_domestic_percent" value="<?=e($val('non_domestic_percent',15))?>"></div><div class="col-md-3"><label class="form-label">Kehilangan air (%)</label><input class="form-control" type="number" step="any" name="water_loss_percent" value="<?=e($val('water_loss_percent',20))?>"></div><div class="col-md-2"><label class="form-label">Faktor hari maks.</label><input class="form-control" type="number" step="any" name="max_day_factor" value="<?=e($val('max_day_factor',1.15))?>"></div><div class="col-md-2"><label class="form-label">Faktor jam puncak</label><input class="form-control" type="number" step="any" name="peak_hour_factor" value="<?=e($val('peak_hour_factor',1.5))?>"></div><div class="col-md-2"><label class="form-label">Kebakaran (L/s)</label><input class="form-control" type="number" step="any" name="fire_flow_lps" value="<?=e($val('fire_flow_lps',0))?>"></div>
  <?php if($a):?><div class="col-12"><div class="result-strip"><div><small>Rata-rata</small><strong><?=number_format((float)$a['average_demand_lps'],3,',','.')?> L/s</strong></div><div><small>Hari maksimum</small><strong><?=number_format((float)$a['max_day_demand_lps'],3,',','.')?> L/s</strong></div><div><small>Jam puncak</small><strong><?=number_format((float)$a['peak_hour_demand_lps'],3,',','.')?> L/s</strong></div><div><small>Debit desain final</small><strong><?=number_format((float)$a['final_design_flow_lps'],3,',','.')?> L/s</strong></div></div></div><?php endif?>
  <div class="col-12"><details><summary>Pola kebutuhan 24 jam</summary><div class="hour-pattern mt-2"><?php $pattern=json_decode((string)($a['hourly_pattern_json']??'[]'),true)?:array_fill(0,24,1);for($h=0;$h<24;$h++):?><label><span><?=str_pad((string)$h,2,'0',STR_PAD_LEFT)?>:00</span><input class="form-control form-control-sm" type="number" step="any" min="0" name="hourly_pattern[]" value="<?=e($pattern[$h]??1)?>"></label><?php endfor?></div></details></div>
</div></section></div>

<div class="tab-pane fade" id="tab-source"><section class="design-card"><header><div><span>LANGKAH 3</span><h3>Sumber energi dan desain reservoir</h3></div></header><div class="row g-3">
 <div class="col-md-4"><label class="form-label">Nama sumber</label><input class="form-control" name="source_name" value="<?=e($val('source_name'))?>"></div><div class="col-md-2"><label class="form-label">Jenis sumber</label><input class="form-control" name="source_type" value="<?=e($val('source_type','Mata air'))?>"></div><div class="col-md-3"><label class="form-label">Basis energi <span class="required-mark">*</span></label><select class="form-select" name="source_energy_basis"><option value="TOTAL_HEAD">Total hydraulic head</option><option value="WATER_LEVEL" <?=$val('source_energy_basis')==='WATER_LEVEL'?'selected':''?>>Elevasi + muka air</option></select></div><div class="col-md-3"><label class="form-label">Sistem suplai</label><select class="form-select" name="source_supply_mode"><option value="GRAVITY">Gravitasi</option><option value="PUMP" <?=$val('source_supply_mode')==='PUMP'?'selected':''?>>Pompa</option></select></div>
 <div class="col-md-2"><label class="form-label">Head total (m)</label><input class="form-control" type="number" step="any" name="source_total_head_m" value="<?=e($val('source_total_head_m',0))?>"></div><div class="col-md-2"><label class="form-label">Level min. (m)</label><input class="form-control" type="number" step="any" name="source_min_level_m" value="<?=e($val('source_min_level_m',0))?>"></div><div class="col-md-2"><label class="form-label">Level normal (m)</label><input class="form-control" type="number" step="any" name="source_normal_level_m" value="<?=e($val('source_normal_level_m',0))?>"></div><div class="col-md-2"><label class="form-label">Level maks. (m)</label><input class="form-control" type="number" step="any" name="source_max_level_m" value="<?=e($val('source_max_level_m',0))?>"></div><div class="col-md-2"><label class="form-label">Debit tersedia (L/s)</label><input class="form-control" type="number" step="any" name="source_available_flow_lps" value="<?=e($val('source_available_flow_lps',0))?>"></div><div class="col-md-2"><label class="form-label">Jam layanan</label><input class="form-control" type="number" step="any" name="source_service_hours" value="<?=e($val('source_service_hours',24))?>"></div>
 <div class="col-12"><hr><h6>Perhitungan volume dan rentang dimensi reservoir</h6></div>
 <div class="col-md-3"><label class="form-label">Metode volume</label><select class="form-select" name="reservoir_method"><option value="DAILY_PERCENT">Persentase kebutuhan harian</option><option value="MASS_CURVE" <?=$val('reservoir_method')==='MASS_CURVE'?'selected':''?>>Kurva massa 24 jam</option><option value="DETENTION_TIME" <?=$val('reservoir_method')==='DETENTION_TIME'?'selected':''?>>Waktu detensi</option></select></div><div class="col-md-3"><label class="form-label">Bentuk</label><select class="form-select" name="reservoir_shape"><option value="RECTANGLE">Persegi panjang</option><option value="SQUARE" <?=$val('reservoir_shape')==='SQUARE'?'selected':''?>>Persegi</option><option value="CYLINDER" <?=$val('reservoir_shape')==='CYLINDER'?'selected':''?>>Silinder</option></select></div><div class="col-md-2"><label class="form-label">Kompartemen</label><input class="form-control" type="number" min="1" name="reservoir_compartments" value="<?=e($val('reservoir_compartments',1))?>"></div><div class="col-md-2"><label class="form-label">Storage (%)</label><input class="form-control" type="number" step="any" name="reservoir_storage_percent" value="<?=e($val('reservoir_storage_percent',20))?>"></div><div class="col-md-2"><label class="form-label">Jam detensi</label><input class="form-control" type="number" step="any" name="reservoir_operating_hours" value="<?=e($val('reservoir_operating_hours',6))?>"></div>
 <div class="col-md-2"><label class="form-label">Cadangan (%)</label><input class="form-control" type="number" step="any" name="reservoir_reserve_percent" value="<?=e($val('reservoir_reserve_percent',10))?>"></div><div class="col-md-2"><label class="form-label">Kebakaran (m³)</label><input class="form-control" type="number" step="any" name="reservoir_fire_volume_m3" value="<?=e($val('reservoir_fire_volume_m3',0))?>"></div><div class="col-md-2"><label class="form-label">Darurat (m³)</label><input class="form-control" type="number" step="any" name="reservoir_emergency_volume_m3" value="<?=e($val('reservoir_emergency_volume_m3',0))?>"></div><div class="col-md-2"><label class="form-label">Volume mati (m³)</label><input class="form-control" type="number" step="any" name="reservoir_dead_volume_m3" value="<?=e($val('reservoir_dead_volume_m3',0))?>"></div><div class="col-md-2"><label class="form-label">Freeboard (m)</label><input class="form-control" type="number" step="any" name="reservoir_freeboard_m" value="<?=e($val('reservoir_freeboard_m',.5))?>"></div><div class="col-md-2"><label class="form-label">Tinggi efektif (m)</label><input class="form-control" type="number" step="any" name="reservoir_effective_height_m" value="<?=e($val('reservoir_effective_height_m',3))?>"></div>
 <?php foreach(['length'=>'Panjang','width'=>'Lebar','side'=>'Sisi','diameter'=>'Diameter','height'=>'Tinggi'] as $key=>$label):?><div class="col-md"><label class="form-label"><?=$label?> min/maks/step (m)</label><div class="input-group"><input class="form-control" type="number" step="any" name="<?=$key?>_min_m" value="<?=e($range[$key.'_min_m']??($key==='height'?2:4))?>"><input class="form-control" type="number" step="any" name="<?=$key?>_max_m" value="<?=e($range[$key.'_max_m']??($key==='height'?6:20))?>"><input class="form-control" type="number" step="any" name="<?=$key?>_step_m" value="<?=e($range[$key.'_step_m']??($key==='height'?.5:1))?>"></div></div><?php endforeach?>
 <?php if($a):?><div class="col-12"><div class="result-strip"><div><small>Volume operasional</small><strong><?=number_format((float)$a['reservoir_operational_volume_m3'],2,',','.')?> m³</strong></div><div><small>Total kebutuhan</small><strong><?=number_format((float)$a['reservoir_total_required_m3'],2,',','.')?> m³</strong></div></div></div><?php endif?>
</div></section></div>

<div class="tab-pane fade" id="tab-criteria"><section class="design-card"><header><div><span>LANGKAH 4</span><h3>Kriteria teknis dan bobot penilaian</h3></div></header><div class="row g-3">
<?php $criterionLabels=['minimum_velocity_mps'=>['Kecepatan minimum','m/s'],'maximum_velocity_mps'=>['Kecepatan maksimum','m/s'],'target_velocity_mps'=>['Target kecepatan','m/s'],'minimum_pressure_m'=>['Tekanan minimum','m'],'target_pressure_m'=>['Target tekanan','m'],'maximum_pressure_m'=>['Tekanan maksimum','m'],'maximum_unit_headloss_m_per_km'=>['Headloss maksimum','m/km'],'pressure_safety_factor'=>['Faktor keamanan tekanan','-'],'continuity_tolerance'=>['Toleransi kontinuitas','L/s'],'energy_tolerance'=>['Toleransi energi','m'],'minimum_demand_velocity_mps'=>['Kecepatan skenario minimum','m/s'],'reservoir_volume_safety_factor'=>['Faktor keamanan volume','-']];foreach($criterionLabels as $key=>[$label,$unit]):?><div class="col-md-3"><label class="form-label"><?=$label?> (<?=$unit?>)</label><input class="form-control" type="number" step="any" name="criteria[<?=$key?>]" value="<?=e($criteria[$key]??0)?>"></div><?php endforeach?>
<div class="col-md-4"><div class="form-check mt-4"><input type="hidden" name="criteria[minimum_velocity_active]" value="0"><input class="form-check-input" type="checkbox" name="criteria[minimum_velocity_active]" value="1" <?=($criteria['minimum_velocity_active']??1)?'checked':''?>><label class="form-check-label">Batas kecepatan minimum aktif</label></div></div><div class="col-md-5"><div class="form-check mt-4"><input type="hidden" name="criteria[allow_low_velocity_minimum_demand]" value="0"><input class="form-check-input" type="checkbox" name="criteria[allow_low_velocity_minimum_demand]" value="1" <?=($criteria['allow_low_velocity_minimum_demand']??1)?'checked':''?>><label class="form-check-label">Izinkan warning kecepatan rendah pada skenario minimum</label></div></div>
<div class="col-12"><h6 class="mt-2">Bobot multi-kriteria (jumlah harus 100%)</h6></div><?php foreach(['cost'=>'Biaya','pressure'=>'Tekanan','velocity'=>'Kecepatan','headloss'=>'Headloss','safety'=>'Keamanan','uniformity'=>'Keseragaman'] as $key=>$label):?><div class="col-md-2"><label class="form-label"><?=$label?> (%)</label><input class="form-control weight-input" type="number" step="any" name="weights[<?=$key?>]" value="<?=e($weights[$key]??0)?>"></div><?php endforeach?><div class="col-12"><small id="weightTotal" class="text-muted"></small></div>
</div></section></div>

<div class="tab-pane fade" id="tab-pipes"><section class="design-card"><header><div><span>LANGKAH 5</span><h3>Pengaturan kandidat per ruas pipa</h3></div><a class="btn btn-sm btn-outline-primary" href="#katalog-pipa">Master diameter</a></header>
<?php if(!$a):?><div class="empty-design"><i class="bi bi-save2"></i><p>Simpan identitas analisis dahulu. Ruas pipa proyek akan dimuat otomatis.</p></div><?php elseif(!$pipeInputs):?><div class="alert alert-info">Belum ada ruas PIPE pada proyek ini. Gambarkan jaringan terlebih dahulu atau simpan lagi untuk sinkronisasi.</div><?php else:?><div class="table-responsive"><table class="table table-sm align-middle design-table"><thead><tr><th>Ruas</th><th>Panjang</th><th>DN min</th><th>DN maks</th><th>Kandidat ukuran</th><th>Kunci</th><th>Minor K</th><th>Kelompok</th><th>Transien</th></tr></thead><tbody><?php foreach($pipeInputs as $p):$pid=(int)$p['network_link_id'];?><tr><td><strong><?=e($p['route_name'])?></strong><small><?=$p['origin_type'].':'.$p['origin_id'].' → '.$p['destination_type'].':'.$p['destination_id']?></small></td><td><?=number_format((float)$p['pipe_length_m'],2,',','.')?> m</td><td><input class="form-control form-control-sm" type="number" step="any" name="pipes[<?=$pid?>][minimum_dn_mm]" value="<?=e($p['minimum_dn_mm'])?>"></td><td><input class="form-control form-control-sm" type="number" step="any" name="pipes[<?=$pid?>][maximum_dn_mm]" value="<?=e($p['maximum_dn_mm'])?>"></td><td><select class="form-select form-select-sm" multiple size="3" name="pipes[<?=$pid?>][allowed_catalog_ids][]"><?php foreach($catalogActive as $c):?><option value="<?=$c['id']?>" <?=in_array((int)$c['id'],$p['allowed_catalog_ids'],true)?'selected':''?>><?=e($c['material'].' DN'.$c['dn_mm'].' (ID '.$c['inside_diameter_mm'].') '.$c['pressure_class'])?></option><?php endforeach?></select></td><td><label class="form-check"><input class="form-check-input" type="checkbox" name="pipes[<?=$pid?>][is_diameter_locked]" <?=$p['is_diameter_locked']?'checked':''?>> Tetap</label><select class="form-select form-select-sm" name="pipes[<?=$pid?>][fixed_catalog_id]"><option value="">—</option><?php foreach($catalogActive as $c):?><option value="<?=$c['id']?>" <?=$p['fixed_catalog_id']==$c['id']?'selected':''?>>DN <?=$c['dn_mm']?> <?=$c['material']?></option><?php endforeach?></select></td><td><input class="form-control form-control-sm" type="number" step="any" name="pipes[<?=$pid?>][minor_loss_coefficient]" value="<?=e($p['minor_loss_coefficient'])?>"></td><td><input class="form-control form-control-sm" name="pipes[<?=$pid?>][diameter_group]" value="<?=e($p['diameter_group'])?>"></td><td><input class="form-check-input" type="checkbox" name="pipes[<?=$pid?>][transient_enabled]" <?=$p['transient_enabled']?'checked':''?> title="Aktifkan cek water hammer"></td></tr><?php endforeach?></tbody></table></div>
<details class="mt-3"><summary class="fw-bold">Data demand sepanjang ruas, fitting, dan water hammer opsional</summary><div class="table-responsive mt-2"><table class="table design-table"><thead><tr><th>Ruas</th><th>Demand sepanjang (L/s)</th><th>Jumlah fitting</th><th>Kecepatan gelombang a (m/s)</th><th>Perubahan V (m/s)</th><th>Waktu tutup katup (s)</th><th>Allowance manual (bar)</th></tr></thead><tbody><?php foreach($pipeInputs as $p):$pid=(int)$p['network_link_id'];?><tr><td><?=e($p['route_name'])?></td><td><input class="form-control form-control-sm" type="number" step="any" name="pipes[<?=$pid?>][demand_along_lps]" value="<?=e($p['demand_along_lps'])?>"></td><td><input class="form-control form-control-sm" type="number" name="pipes[<?=$pid?>][fitting_count]" value="<?=e($p['fitting_count'])?>"></td><td><input class="form-control form-control-sm" type="number" step="any" name="pipes[<?=$pid?>][wave_speed_mps]" value="<?=e($p['wave_speed_mps'])?>"></td><td><input class="form-control form-control-sm" type="number" step="any" name="pipes[<?=$pid?>][velocity_change_mps]" value="<?=e($p['velocity_change_mps'])?>"></td><td><input class="form-control form-control-sm" type="number" step="any" name="pipes[<?=$pid?>][valve_closure_seconds]" value="<?=e($p['valve_closure_seconds'])?>"></td><td><input class="form-control form-control-sm" type="number" step="any" name="pipes[<?=$pid?>][pressure_allowance_bar]" value="<?=e($p['pressure_allowance_bar'])?>"></td></tr><?php endforeach?></tbody></table></div></details><?php endif?>
</section></div>

<div class="tab-pane fade" id="tab-scenarios"><section class="design-card"><header><div><span>LANGKAH 6</span><h3>Skenario wajib untuk validasi</h3></div><button class="btn btn-sm btn-outline-primary" type="button" id="addScenario"><i class="bi bi-plus"></i> Tambah</button></header>
<div class="table-responsive"><table class="table design-table" id="scenarioTable"><thead><tr><th>Kode</th><th>Nama</th><th>Jenis</th><th>Faktor demand</th><th>Δ head sumber</th><th>Debit kebakaran</th><th>Aktif</th><th>Wajib</th><th></th></tr></thead><tbody><?php $rows=$scenarios?:[['code'=>'AVG','name'=>'Debit rata-rata','scenario_type'=>'AVERAGE','demand_multiplier'=>.6,'source_head_adjustment_m'=>0,'fire_flow_lps'=>0,'is_active'=>1,'is_required'=>1],['code'=>'PEAK','name'=>'Jam puncak','scenario_type'=>'PEAK_HOUR','demand_multiplier'=>1,'source_head_adjustment_m'=>0,'fire_flow_lps'=>0,'is_active'=>1,'is_required'=>1],['code'=>'MIN','name'=>'Debit minimum','scenario_type'=>'MINIMUM_DEMAND','demand_multiplier'=>.3,'source_head_adjustment_m'=>0,'fire_flow_lps'=>0,'is_active'=>1,'is_required'=>1]];foreach($rows as $i=>$s):?><tr><td><input class="form-control form-control-sm" name="scenarios[<?=$i?>][code]" value="<?=e($s['code'])?>"></td><td><input class="form-control form-control-sm" name="scenarios[<?=$i?>][name]" value="<?=e($s['name'])?>"></td><td><select class="form-select form-select-sm" name="scenarios[<?=$i?>][scenario_type]"><?php foreach(['AVERAGE','MAXIMUM_DAY','PEAK_HOUR','MINIMUM_DEMAND','MINIMUM_SOURCE_LEVEL','MAXIMUM_SOURCE_LEVEL','FIRE','OUTAGE','CUSTOM'] as $t):?><option <?=$s['scenario_type']===$t?'selected':''?>><?=$t?></option><?php endforeach?></select></td><td><input class="form-control form-control-sm" type="number" step="any" name="scenarios[<?=$i?>][demand_multiplier]" value="<?=e($s['demand_multiplier'])?>"></td><td><input class="form-control form-control-sm" type="number" step="any" name="scenarios[<?=$i?>][source_head_adjustment_m]" value="<?=e($s['source_head_adjustment_m'])?>"></td><td><input class="form-control form-control-sm" type="number" step="any" name="scenarios[<?=$i?>][fire_flow_lps]" value="<?=e($s['fire_flow_lps'])?>"></td><td><input class="form-check-input" type="checkbox" name="scenarios[<?=$i?>][is_active]" <?=$s['is_active']?'checked':''?>></td><td><input class="form-check-input" type="checkbox" name="scenarios[<?=$i?>][is_required]" <?=$s['is_required']?'checked':''?>></td><td><button class="btn btn-sm btn-outline-danger remove-scenario" type="button"><i class="bi bi-trash"></i></button></td></tr><?php endforeach?></tbody></table></div>
<div class="row g-3"><div class="col-md-3"><label class="form-label">Maks. alternatif</label><input class="form-control" type="number" name="max_alternatives" value="<?=e($val('max_alternatives',10))?>"></div><div class="col-md-3"><label class="form-label">Maks. iterasi</label><input class="form-control" type="number" name="max_iterations" value="<?=e($val('max_iterations',100))?>"></div><div class="col-md-3"><label class="form-label">Maks. kombinasi</label><input class="form-control" type="number" name="max_combinations" value="<?=e($val('max_combinations',500))?>"></div><div class="col-md-3"><label class="form-label">Timeout (detik)</label><input class="form-control" type="number" name="calculation_timeout_seconds" value="<?=e($val('calculation_timeout_seconds',120))?>"></div></div>
</section></div>

<div class="tab-pane fade" id="tab-results"><section class="design-card" id="hasil-desain"><header><div><span>LANGKAH 7</span><h3>Alternatif dan rekomendasi</h3></div><?php if($a):?><button form="runAutomaticDesign" class="btn btn-primary"><i class="bi bi-cpu"></i> Jalankan Desain</button><?php endif?></header>
<?php if(!$alternatives):?><div class="empty-design"><i class="bi bi-bar-chart-line"></i><p>Simpan konfigurasi lalu jalankan desain. Hanya alternatif yang konvergen dan lolos kriteria yang dapat direkomendasikan.</p></div><?php else:?><div class="row g-3 mb-3"><div class="col-lg-7"><div class="chart-box"><canvas id="alternativeChart"></canvas></div></div><div class="col-lg-5"><div class="recommendation-box"><i class="bi bi-patch-check-fill"></i><?php $rec=current(array_filter($alternatives,fn($x)=>(int)$x['is_recommended']===1));?><span>Rekomendasi sistem</span><strong><?=e($rec['combination_code']??'Tidak ada alternatif yang lolos')?></strong><small><?=isset($rec['total_cost'])?'Estimasi pipa Rp '.number_format((float)$rec['total_cost'],0,',','.'):'Periksa alasan kegagalan pada tabel.'?></small></div></div></div>
<div class="table-responsive"><table class="table design-table"><thead><tr><th>Peringkat</th><th>Alternatif</th><th>Biaya pipa</th><th>P min–maks</th><th>V min–maks</th><th>Headloss</th><th>Skor</th><th>Status</th><th>Pilihan</th></tr></thead><tbody><?php foreach($alternatives as $alt):?><tr class="<?=$alt['is_recommended']?'table-success':''?>"><td>#<?=$alt['rank_number']?></td><td><strong><?=e($alt['combination_code'])?></strong><?=$alt['is_recommended']?'<small class="text-success">Direkomendasikan</small>':''?></td><td>Rp <?=number_format((float)$alt['total_cost'],0,',','.')?></td><td><?=number_format((float)$alt['minimum_pressure_m'],2,',','.')?>–<?=number_format((float)$alt['maximum_pressure_m'],2,',','.')?> m</td><td><?=number_format((float)$alt['minimum_velocity_mps'],2,',','.')?>–<?=number_format((float)$alt['maximum_velocity_mps'],2,',','.')?> m/s</td><td><?=number_format((float)$alt['total_headloss_m'],3,',','.')?> m</td><td><?=number_format((float)$alt['technical_score'],2,',','.')?></td><td><span class="badge text-bg-<?=$statusClass($alt['status'])?>"><?=$alt['status']?></span><?php if($alt['failure_reasons']):?><details><summary>Alasan</summary><small><?=nl2br(e($alt['failure_reasons']))?></small></details><?php endif?></td><td><?php if(in_array($alt['status'],['PASS','WARNING'],true)):?><button form="selectPipe<?=$alt['id']?>" class="btn btn-sm <?=$alt['is_selected']?'btn-success':'btn-outline-success'?>"><?=$alt['is_selected']?'Terpilih':'Pilih'?></button><?php endif?></td></tr><?php endforeach?></tbody></table></div><?php endif?>
<?php if($reservoirAlternatives):?><h5 class="mt-4">Alternatif dimensi reservoir</h5><div class="table-responsive"><table class="table design-table"><thead><tr><th>Rank</th><th>Bentuk</th><th>Dimensi efektif</th><th>Freeboard</th><th>Kompartemen</th><th>Volume</th><th>Selisih</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($reservoirAlternatives as $r):?><tr><td>#<?=$r['rank_number']?></td><td><?=$r['shape']?></td><td><?=$r['length_or_diameter_m']?> × <?=($r['width_m']??'—')?> × <?=$r['effective_height_m']?> m</td><td><?=$r['freeboard_m']?> m</td><td><?=$r['compartments']?></td><td><?=number_format((float)$r['effective_volume_m3'],2,',','.')?> m³</td><td><?=number_format((float)$r['excess_volume_m3'],2,',','.')?> m³</td><td><span class="badge text-bg-success"><?=$r['status']?></span></td><td><button form="selectReservoir<?=$r['id']?>" class="btn btn-sm <?=$r['is_selected']?'btn-success':'btn-outline-success'?>"><?=$r['is_selected']?'Terpilih':'Pilih'?></button></td></tr><?php endforeach?></tbody></table></div><?php endif?>
</section></div>
</div>
<?php if(!empty($selectedPipes)||!empty($selectedNodes)):?>
<section class="design-card mt-3"><header><div><span>DETAIL ALTERNATIF TERPILIH / REKOMENDASI</span><h3>Hasil per ruas dan node</h3></div><?php if(!empty($a['selected_alternative_id'])&&has_role(['super_admin','administrator'])):?><button class="btn btn-success" form="applyAutomaticDesign" onclick="return confirm('Terapkan diameter alternatif terpilih ke jaringan proyek?')"><i class="bi bi-check2-square"></i> Terapkan ke Proyek</button><?php endif?></header>
 <div class="row g-3 mb-3"><div class="col-lg-3"><div class="chart-box"><canvas id="hglChart"></canvas></div></div><div class="col-lg-3"><div class="chart-box"><canvas id="pressureChart"></canvas></div></div><div class="col-lg-3"><div class="chart-box"><canvas id="velocityChart"></canvas></div></div><div class="col-lg-3"><div class="chart-box"><canvas id="headlossChart"></canvas></div></div></div>
 <details open><summary class="fw-bold mb-2">Detail pipa per skenario (<?=count($selectedPipes)?> baris)</summary><div class="table-responsive"><table class="table design-table"><thead><tr><th>Skenario</th><th>Ruas</th><th>Material / DN / ID</th><th>Debit</th><th>Kecepatan</th><th>Headloss</th><th>m/km</th><th>Tekanan awal–akhir</th><th>PN</th><th>Status</th></tr></thead><tbody><?php foreach($selectedPipes as $p):?><tr><td><?=e($p['scenario_code'])?></td><td><?=e($p['route_name']??('Ruas '.$p['network_link_id']))?></td><td><?=e(($p['material']??'—').' / '.$p['dn_mm'].' / '.$p['inside_diameter_mm'].' mm')?></td><td><?=number_format((float)$p['flow_lps'],3,',','.')?> L/s</td><td><?=number_format((float)$p['velocity_mps'],3,',','.')?> m/s</td><td><?=number_format((float)$p['major_headloss_m']+(float)$p['minor_headloss_m'],3,',','.')?> m</td><td><?=number_format((float)$p['unit_headloss_m_per_km'],3,',','.')?></td><td><?=number_format((float)$p['start_pressure_m'],2,',','.')?>–<?=number_format((float)$p['end_pressure_m'],2,',','.')?> m</td><td><?=e($p['pressure_class'])?></td><td><span class="badge text-bg-<?=$statusClass($p['status']==='PASS'?'PASS':($p['status']==='VELOCITY_LOW'?'WARNING':'FAIL'))?>"><?=e($p['status'])?></span></td></tr><?php endforeach?></tbody></table></div></details>
 <details class="mt-3"><summary class="fw-bold mb-2">Detail node per skenario (<?=count($selectedNodes)?> baris)</summary><div class="table-responsive"><table class="table design-table"><thead><tr><th>Skenario</th><th>Node</th><th>Elevasi</th><th>Demand</th><th>Head</th><th>Tekanan m</th><th>kPa</th><th>bar</th><th>Status</th></tr></thead><tbody><?php foreach($selectedNodes as $n):?><tr><td><?=e($n['scenario_code'])?></td><td><?=e($n['node_name'])?></td><td><?=$n['elevation_m']?> m</td><td><?=$n['demand_lps']?> L/s</td><td><?=$n['hydraulic_head_m']?> m</td><td><?=$n['pressure_m']?></td><td><?=$n['pressure_kpa']?></td><td><?=$n['pressure_bar']?></td><td><?=e($n['status'])?></td></tr><?php endforeach?></tbody></table></div></details>
</section><?php endif?>
<div class="sticky-design-actions"><span id="unsavedIndicator"><i class="bi bi-cloud-check"></i> Data siap disimpan</span><button class="btn btn-primary" type="submit"><i class="bi bi-save"></i> Simpan Konfigurasi</button><?php if($a):?><button class="btn btn-dark" type="submit" form="runAutomaticDesign"><i class="bi bi-cpu"></i> Jalankan</button><?php endif?></div>
</form>
<?php if($a):?><form id="runAutomaticDesign" method="post" action="<?=url('automatic-design/run')?>"><?=csrf_field()?><input type="hidden" name="analysis_id" value="<?=$a['id']?>"></form><form id="applyAutomaticDesign" method="post" action="<?=url('automatic-design/apply')?>"><?=csrf_field()?><input type="hidden" name="analysis_id" value="<?=$a['id']?>"></form><?php foreach($alternatives as $alt):?><form id="selectPipe<?=$alt['id']?>" method="post" action="<?=url('automatic-design/select')?>"><?=csrf_field()?><input type="hidden" name="analysis_id" value="<?=$a['id']?>"><input type="hidden" name="selection_type" value="pipe"><input type="hidden" name="selected_id" value="<?=$alt['id']?>"></form><?php endforeach?><?php foreach($reservoirAlternatives as $r):?><form id="selectReservoir<?=$r['id']?>" method="post" action="<?=url('automatic-design/select')?>"><?=csrf_field()?><input type="hidden" name="analysis_id" value="<?=$a['id']?>"><input type="hidden" name="selection_type" value="reservoir"><input type="hidden" name="selected_id" value="<?=$r['id']?>"></form><?php endforeach?><?php endif?>

<section class="design-card mt-4" id="katalog-pipa"><header><div><span>MASTER DATA</span><h3>Katalog diameter dan kelas tekanan</h3></div></header><div class="table-responsive"><table class="table design-table"><thead><tr><th>Material</th><th>DN</th><th>OD</th><th>Tebal</th><th>ID dipakai hitung</th><th>Kelas</th><th>Tekanan</th><th>C</th><th>ε</th><th>Harga/m</th><th>Status</th></tr></thead><tbody><?php foreach($catalog as $c):?><tr><td><?=e($c['material'])?></td><td><?=$c['dn_mm']?> mm</td><td><?=$c['outside_diameter_mm']?> mm</td><td><?=$c['wall_thickness_mm']?> mm</td><td><strong><?=$c['inside_diameter_mm']?> mm</strong></td><td><?=e($c['pressure_class'])?></td><td><?=$c['allowable_pressure_bar']?> bar</td><td><?=$c['hazen_williams_c']?></td><td><?=$c['darcy_roughness_mm']?> mm</td><td>Rp <?=number_format((float)$c['price_per_meter'],0,',','.')?></td><td><span class="badge text-bg-<?=$c['is_active']?'success':'secondary'?>"><?=$c['is_active']?'Aktif':'Arsip'?></span></td></tr><?php endforeach?></tbody></table></div>
<?php if(has_role(['super_admin','administrator'])):?><details class="mt-3"><summary class="btn btn-outline-primary">Tambah atau edit ukuran</summary><form id="catalogForm" method="post" action="<?=url('automatic-design/catalog')?>" class="row g-2 mt-2"><?=csrf_field()?><div class="col-12"><label class="form-label">Pilih ukuran untuk diedit, atau pilih data baru</label><select class="form-select" name="catalog_id" id="catalogPicker"><option value="">Data baru</option><?php foreach($catalog as $c):?><option value="<?=$c['id']?>" data-row="<?=e(json_encode($c,JSON_UNESCAPED_UNICODE))?>"><?=e($c['material'].' DN '.$c['dn_mm'].' '.$c['pressure_class'])?></option><?php endforeach?></select></div><?php foreach(['material'=>'Material *','dn_mm'=>'DN (mm) *','outside_diameter_mm'=>'OD (mm)','wall_thickness_mm'=>'Tebal (mm)','inside_diameter_mm'=>'ID (mm) *','pressure_class'=>'Kelas tekanan *','allowable_pressure_bar'=>'Tekanan izin (bar)','hazen_williams_c'=>'Hazen C','darcy_roughness_mm'=>'Kekasaran ε (mm)','price_per_meter'=>'Harga/m'] as $k=>$label):?><div class="col-md-2"><label class="form-label"><?=$label?></label><input class="form-control" name="<?=$k?>" <?=$k==='material'||$k==='pressure_class'?'type="text"':'type="number" step="any"'?> <?=str_contains($label,'*')?'required':''?>></div><?php endforeach?><div class="col-md-4"><label class="form-label">Keterangan</label><input class="form-control" name="description"></div><div class="col-md-2 d-flex align-items-end"><button class="btn btn-primary w-100">Simpan katalog</button></div></form></details><?php endif?>
</section>
<script>
document.addEventListener('DOMContentLoaded',()=>{
 const form=document.getElementById('automaticDesignForm'),indicator=document.getElementById('unsavedIndicator');form?.addEventListener('input',()=>indicator.innerHTML='<i class="bi bi-exclamation-circle"></i> Ada perubahan belum disimpan');
 document.getElementById('catalogPicker')?.addEventListener('change',e=>{const row=e.target.selectedOptions[0]?.dataset.row?JSON.parse(e.target.selectedOptions[0].dataset.row):{};['material','dn_mm','outside_diameter_mm','wall_thickness_mm','inside_diameter_mm','pressure_class','allowable_pressure_bar','hazen_williams_c','darcy_roughness_mm','price_per_meter','description'].forEach(key=>{const field=document.querySelector('#catalogForm [name="'+key+'"]');if(field)field.value=row[key]??'';});});
 const updateWeights=()=>{const total=[...document.querySelectorAll('.weight-input')].reduce((s,x)=>s+(parseFloat(x.value)||0),0),el=document.getElementById('weightTotal');if(el){el.textContent='Jumlah bobot: '+total.toFixed(1)+'%';el.className=Math.abs(total-100)<.01?'text-success':'text-danger';}};document.querySelectorAll('.weight-input').forEach(x=>x.addEventListener('input',updateWeights));updateWeights();
 let nextScenario=document.querySelectorAll('#scenarioTable tbody tr').length;document.getElementById('addScenario')?.addEventListener('click',()=>{const i=nextScenario++,tr=document.createElement('tr');tr.innerHTML=`<td><input class="form-control form-control-sm" name="scenarios[${i}][code]" value="CUSTOM-${i+1}"></td><td><input class="form-control form-control-sm" name="scenarios[${i}][name]" value="Skenario baru"></td><td><select class="form-select form-select-sm" name="scenarios[${i}][scenario_type]"><option>CUSTOM</option><option>FIRE</option><option>OUTAGE</option></select></td><td><input class="form-control form-control-sm" type="number" step="any" name="scenarios[${i}][demand_multiplier]" value="1"></td><td><input class="form-control form-control-sm" type="number" step="any" name="scenarios[${i}][source_head_adjustment_m]" value="0"></td><td><input class="form-control form-control-sm" type="number" step="any" name="scenarios[${i}][fire_flow_lps]" value="0"></td><td><input class="form-check-input" type="checkbox" name="scenarios[${i}][is_active]" checked></td><td><input class="form-check-input" type="checkbox" name="scenarios[${i}][is_required]" checked></td><td><button class="btn btn-sm btn-outline-danger remove-scenario" type="button"><i class="bi bi-trash"></i></button></td>`;document.querySelector('#scenarioTable tbody').appendChild(tr);});
 document.addEventListener('click',e=>{if(e.target.closest('.remove-scenario'))e.target.closest('tr').remove();});
 <?php if($alternatives):?>new Chart(document.getElementById('alternativeChart'),{type:'bar',data:{labels:<?=json_encode(array_column($alternatives,'combination_code'))?>,datasets:[{label:'Tekanan minimum (m)',data:<?=json_encode(array_map('floatval',array_column($alternatives,'minimum_pressure_m')))?>,backgroundColor:'#0d6efd'},{label:'Kecepatan maksimum (m/s)',data:<?=json_encode(array_map('floatval',array_column($alternatives,'maximum_velocity_mps')))?>,backgroundColor:'#10b981'}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:'bottom'}}}});<?php endif?>
 <?php if(!empty($selectedNodes)):?>new Chart(document.getElementById('hglChart'),{type:'line',data:{labels:<?=json_encode(array_column($selectedNodes,'node_name'))?>,datasets:[{label:'Hydraulic head (m)',data:<?=json_encode(array_map('floatval',array_column($selectedNodes,'hydraulic_head_m')))?>,borderColor:'#0d6efd'},{label:'Elevasi (m)',data:<?=json_encode(array_map('floatval',array_column($selectedNodes,'elevation_m')))?>,borderColor:'#7950f2'}]},options:{responsive:true,maintainAspectRatio:false}});new Chart(document.getElementById('pressureChart'),{type:'line',data:{labels:<?=json_encode(array_column($selectedNodes,'node_name'))?>,datasets:[{label:'Tekanan node (m)',data:<?=json_encode(array_map('floatval',array_column($selectedNodes,'pressure_m')))?>,borderColor:'#0d6efd',backgroundColor:'#0d6efd22',fill:true}]},options:{responsive:true,maintainAspectRatio:false}});<?php endif?>
 <?php if(!empty($selectedPipes)):?>new Chart(document.getElementById('velocityChart'),{type:'bar',data:{labels:<?=json_encode(array_column($selectedPipes,'route_name'))?>,datasets:[{label:'Kecepatan (m/s)',data:<?=json_encode(array_map('floatval',array_column($selectedPipes,'velocity_mps')))?>,backgroundColor:'#10b981'}]},options:{responsive:true,maintainAspectRatio:false}});new Chart(document.getElementById('headlossChart'),{type:'bar',data:{labels:<?=json_encode(array_column($selectedPipes,'route_name'))?>,datasets:[{label:'Headloss (m/km)',data:<?=json_encode(array_map('floatval',array_column($selectedPipes,'unit_headloss_m_per_km')))?>,backgroundColor:'#f59e0b'}]},options:{responsive:true,maintainAspectRatio:false}});<?php endif?>
});
</script>
